
SET statement_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;

-- ==============================================================================
-- LIMPIEZA COMPLETA DE TABLAS E REINICIO DE SECUENCIAS DE IDs (CASCADE)
-- ==============================================================================
TRUNCATE TABLE 
    public.cache_afinidad,
    public.habilidades_vacante,
    public.habilidades_estudiante,
    public.habilidades,
    public.vacantes,
    public.perfiles_gestor,
    public.perfiles_estudiante,
    public.supervisores,
    public.instituciones,
    public.usuarios,
    public.roles,
    public.carreras,
    public.facultades
RESTART IDENTITY CASCADE;

-- ==========================================
-- DATOS TABLA: public.facultades
-- ==========================================
INSERT INTO public.facultades (facultad_id, nombre, activo) VALUES (1, 'Ciencias Matemáticas y Físicas', true);
INSERT INTO public.facultades (facultad_id, nombre, activo) VALUES (2, 'Ingeniería Química', true);

-- ==========================================
-- DATOS TABLA: public.carreras
-- ==========================================
INSERT INTO public.carreras (carrera_id, facultad_id, nombre, codigo, activo) VALUES (1, 1, 'SOFTWARE', 'SOF', true);
INSERT INTO public.carreras (carrera_id, facultad_id, nombre, codigo, activo) VALUES (2, 1, 'Ciencias de Datos e Inteligencia Artificial', 'CDIA', true);
INSERT INTO public.carreras (carrera_id, facultad_id, nombre, codigo, activo) VALUES (3, 2, 'Ingeniería de la Producción', 'INP', true);

-- ==========================================
-- DATOS TABLA: public.roles
-- ==========================================
INSERT INTO public.roles (rol_id, nombre, descripcion) VALUES (1, 'estudiante', 'Estudiante de la Carrera');
INSERT INTO public.roles (rol_id, nombre, descripcion) VALUES (2, 'empresa', 'Empresa o Institución con convenio');
INSERT INTO public.roles (rol_id, nombre, descripcion) VALUES (3, 'gestor', 'Gestor de practicas preprofesionales');
INSERT INTO public.roles (rol_id, nombre, descripcion) VALUES (4, 'admin', 'Administrador tecnico del sistema');

-- ==========================================
-- DATOS TABLA: public.usuarios
-- ==========================================
INSERT INTO public.usuarios (usuario_id, cedula, contrasena, nombre, apellido, correo, telefono, rol_id, foto_perfil, activo, creado_en, actualizado_en) VALUES (1, '0900000001', '$2b$12$N1z3kpDufIcmwp7xTnt.u.ufRsPGZ7cJDBU1VXpZR/N1nsTpSIK.e', 'Admin', 'Sistema', 'admin@ug.edu.ec', '0999000000', 4, NULL, true, '2026-06-03 23:07:05', '2026-06-03 23:07:05');
INSERT INTO public.usuarios (usuario_id, cedula, contrasena, nombre, apellido, correo, telefono, rol_id, foto_perfil, activo, creado_en, actualizado_en) VALUES (4, '0900000004', '$2b$12$N1z3kpDufIcmwp7xTnt.u.ufRsPGZ7cJDBU1VXpZR/N1nsTpSIK.e', 'Luisa', 'Méndez', 'luisa.mendez@ug.edu.ec', '0997777773', 3, NULL, true, '2026-06-03 23:07:05', '2026-06-03 23:07:05');
INSERT INTO public.usuarios (usuario_id, cedula, contrasena, nombre, apellido, correo, telefono, rol_id, foto_perfil, activo, creado_en, actualizado_en) VALUES (7, '1312657255', '$2b$12$N1z3kpDufIcmwp7xTnt.u.ufRsPGZ7cJDBU1VXpZR/N1nsTpSIK.e', 'Jorge David', 'Intriago Loor', 'jorge.intriagoloo@ug.edu.ec', '09900007', 1, NULL, true, '2026-06-03 23:07:05', '2026-06-03 23:07:05');
INSERT INTO public.usuarios (usuario_id, cedula, contrasena, nombre, apellido, correo, telefono, rol_id, foto_perfil, activo, creado_en, actualizado_en) VALUES (8, '0911223344', '$2b$12$N1z3kpDufIcmwp7xTnt.u.ufRsPGZ7cJDBU1VXpZR/N1nsTpSIK.e', 'Maria Fernanda', 'Gómez Silva', 'maria.gomez@ug.edu.ec', '09900008', 1, NULL, true, '2026-06-03 23:07:05', '2026-06-03 23:07:05');
INSERT INTO public.usuarios (usuario_id, cedula, contrasena, nombre, apellido, correo, telefono, rol_id, foto_perfil, activo, creado_en, actualizado_en) VALUES (9, '0922334455', '$2b$12$N1z3kpDufIcmwp7xTnt.u.ufRsPGZ7cJDBU1VXpZR/N1nsTpSIK.e', 'Luis Antonio', 'Pérez Castro', 'luis.perez@ug.edu.ec', '09900009', 1, NULL, true, '2026-06-03 23:07:05', '2026-06-03 23:07:05');
INSERT INTO public.usuarios (usuario_id, cedula, contrasena, nombre, apellido, correo, telefono, rol_id, foto_perfil, activo, creado_en, actualizado_en) VALUES (10, '0933445566', '$2b$12$N1z3kpDufIcmwp7xTnt.u.ufRsPGZ7cJDBU1VXpZR/N1nsTpSIK.e', 'Ana Sofía', 'Martínez Vera', 'ana.martinez@ug.edu.ec', '099000010', 1, NULL, true, '2026-06-03 23:07:05', '2026-06-03 23:07:05');
INSERT INTO public.usuarios (usuario_id, cedula, contrasena, nombre, apellido, correo, telefono, rol_id, foto_perfil, activo, creado_en, actualizado_en) VALUES (12, '0955667788', '$2b$12$N1z3kpDufIcmwp7xTnt.u.ufRsPGZ7cJDBU1VXpZR/N1nsTpSIK.e', 'Gabriela Elena', 'Vera Loor', 'gabriela.vera@ug.edu.ec', '099000012', 1, NULL, true, '2026-06-03 23:07:05', '2026-06-03 23:07:05');
INSERT INTO public.usuarios (usuario_id, cedula, contrasena, nombre, apellido, correo, telefono, rol_id, foto_perfil, activo, creado_en, actualizado_en) VALUES (13, '0966778899', '$2b$12$N1z3kpDufIcmwp7xTnt.u.ufRsPGZ7cJDBU1VXpZR/N1nsTpSIK.e', 'Carlos Alberto', 'Mora Sánchez', 'carlos.mora@ug.edu.ec', '099000013', 1, NULL, true, '2026-06-03 23:07:05', '2026-06-03 23:07:05');
INSERT INTO public.usuarios (usuario_id, cedula, contrasena, nombre, apellido, correo, telefono, rol_id, foto_perfil, activo, creado_en, actualizado_en) VALUES (14, '0977889900', '$2b$12$N1z3kpDufIcmwp7xTnt.u.ufRsPGZ7cJDBU1VXpZR/N1nsTpSIK.e', 'Diana Carolina', 'Silva Torres', 'diana.silva@ug.edu.ec', '099000014', 1, NULL, true, '2026-06-03 23:07:05', '2026-06-03 23:07:05');
INSERT INTO public.usuarios (usuario_id, cedula, contrasena, nombre, apellido, correo, telefono, rol_id, foto_perfil, activo, creado_en, actualizado_en) VALUES (16, '0990161100', '$2b$12$N1z3kpDufIcmwp7xTnt.u.ufRsPGZ7cJDBU1VXpZR/N1nsTpSIK.e', 'Pedro', 'Sanchez', 'contacto@innovasoft.com', '099000016', 2, NULL, true, '2026-06-03 23:07:05', '2026-06-03 23:07:05');
INSERT INTO public.usuarios (usuario_id, cedula, contrasena, nombre, apellido, correo, telefono, rol_id, foto_perfil, activo, creado_en, actualizado_en) VALUES (18, '0990181100', '$2b$12$N1z3kpDufIcmwp7xTnt.u.ufRsPGZ7cJDBU1VXpZR/N1nsTpSIK.e', 'Carla', 'Ruiz', 'rrhh@clouddevs.com', '099000018', 2, NULL, true, '2026-06-03 23:07:05', '2026-06-03 23:07:05');
INSERT INTO public.usuarios (usuario_id, cedula, contrasena, nombre, apellido, correo, telefono, rol_id, foto_perfil, activo, creado_en, actualizado_en) VALUES (19, '0990191100', '$2b$12$N1z3kpDufIcmwp7xTnt.u.ufRsPGZ7cJDBU1VXpZR/N1nsTpSIK.e', 'Jorge', 'Moreno', 'rrhh@appworks.com', '099000019', 2, NULL, true, '2026-06-03 23:07:05', '2026-06-03 23:07:05');
INSERT INTO public.usuarios (usuario_id, cedula, contrasena, nombre, apellido, correo, telefono, rol_id, foto_perfil, activo, creado_en, actualizado_en) VALUES (20, '0990201100', '$2b$12$N1z3kpDufIcmwp7xTnt.u.ufRsPGZ7cJDBU1VXpZR/N1nsTpSIK.e', 'Elena', 'Vargas', 'rrhh@fintechsolutions.com', '099000020', 2, NULL, true, '2026-06-03 23:07:05', '2026-06-03 23:07:05');
INSERT INTO public.usuarios (usuario_id, cedula, contrasena, nombre, apellido, correo, telefono, rol_id, foto_perfil, activo, creado_en, actualizado_en) VALUES (21, '0990211100', '$2b$12$N1z3kpDufIcmwp7xTnt.u.ufRsPGZ7cJDBU1VXpZR/N1nsTpSIK.e', 'Andres', 'Rojas', 'rrhh@cybersecurityec.com', '099000021', 2, NULL, true, '2026-06-03 23:07:05', '2026-06-03 23:07:05');
INSERT INTO public.usuarios (usuario_id, cedula, contrasena, nombre, apellido, correo, telefono, rol_id, foto_perfil, activo, creado_en, actualizado_en) VALUES (22, '0990221100', '$2b$12$N1z3kpDufIcmwp7xTnt.u.ufRsPGZ7cJDBU1VXpZR/N1nsTpSIK.e', 'Sofia', 'Mendoza', 'rrhh@smartcode.com', '099000022', 2, NULL, true, '2026-06-03 23:07:05', '2026-06-03 23:07:05');
INSERT INTO public.usuarios (usuario_id, cedula, contrasena, nombre, apellido, correo, telefono, rol_id, foto_perfil, activo, creado_en, actualizado_en) VALUES (23, '0990231100', '$2b$12$N1z3kpDufIcmwp7xTnt.u.ufRsPGZ7cJDBU1VXpZR/N1nsTpSIK.e', 'Mario', 'Castro', 'rrhh@nexustech.com', '099000023', 2, NULL, true, '2026-06-03 23:07:05', '2026-06-03 23:07:05');
INSERT INTO public.usuarios (usuario_id, cedula, contrasena, nombre, apellido, correo, telefono, rol_id, foto_perfil, activo, creado_en, actualizado_en) VALUES (24, '0990241100', '$2b$12$N1z3kpDufIcmwp7xTnt.u.ufRsPGZ7cJDBU1VXpZR/N1nsTpSIK.e', 'Laura', 'Guzman', 'rrhh@devmasters.com', '099000024', 2, NULL, true, '2026-06-03 23:07:05', '2026-06-03 23:07:05');
INSERT INTO public.usuarios (usuario_id, cedula, contrasena, nombre, apellido, correo, telefono, rol_id, foto_perfil, activo, creado_en, actualizado_en) VALUES (25, '0990251100', '$2b$12$N1z3kpDufIcmwp7xTnt.u.ufRsPGZ7cJDBU1VXpZR/N1nsTpSIK.e', 'Roberto', 'Luna', 'rrhh@datamindgye.com', '099000025', 2, NULL, true, '2026-06-03 23:07:05', '2026-06-03 23:07:05');
INSERT INTO public.usuarios (usuario_id, cedula, contrasena, nombre, apellido, correo, telefono, rol_id, foto_perfil, activo, creado_en, actualizado_en) VALUES (26, '0990261100', '$2b$12$N1z3kpDufIcmwp7xTnt.u.ufRsPGZ7cJDBU1VXpZR/N1nsTpSIK.e', 'Valeria', 'Pinto', 'contacto@aivision.com', '099000026', 2, NULL, true, '2026-06-03 23:07:05', '2026-06-03 23:07:05');
INSERT INTO public.usuarios (usuario_id, cedula, contrasena, nombre, apellido, correo, telefono, rol_id, foto_perfil, activo, creado_en, actualizado_en) VALUES (27, '0990271100', '$2b$12$N1z3kpDufIcmwp7xTnt.u.ufRsPGZ7cJDBU1VXpZR/N1nsTpSIK.e', 'Jose', 'Mieles', 'rrhh@metricasec.com', '099000027', 2, NULL, true, '2026-06-03 23:07:05', '2026-06-03 23:07:05');
INSERT INTO public.usuarios (usuario_id, cedula, contrasena, nombre, apellido, correo, telefono, rol_id, foto_perfil, activo, creado_en, actualizado_en) VALUES (28, '0990281100', '$2b$12$N1z3kpDufIcmwp7xTnt.u.ufRsPGZ7cJDBU1VXpZR/N1nsTpSIK.e', 'Carmen', 'Salas', 'rrhh@induproduccion.com', '099000028', 2, NULL, true, '2026-06-03 23:07:05', '2026-06-03 23:07:05');
INSERT INTO public.usuarios (usuario_id, cedula, contrasena, nombre, apellido, correo, telefono, rol_id, foto_perfil, activo, creado_en, actualizado_en) VALUES (5, '0955236773', '$2b$12$N1z3kpDufIcmwp7xTnt.u.ufRsPGZ7cJDBU1VXpZR/N1nsTpSIK.e', 'Bryan Guillermo', 'Galarza Indacochea', 'bryan.galarzaind@ug.edu.ec', '09900005', 1, NULL, true, '2026-06-03 23:07:05', '2026-06-24 00:13:06');
INSERT INTO public.usuarios (usuario_id, cedula, contrasena, nombre, apellido, correo, telefono, rol_id, foto_perfil, activo, creado_en, actualizado_en) VALUES (3, '0900000003', '$2b$12$N1z3kpDufIcmwp7xTnt.u.ufRsPGZ7cJDBU1VXpZR/N1nsTpSIK.e', 'Carlos Eduardo', 'Ruiz', 'naldo.anchundiac@ug.edu.ec', '0997777772', 3, NULL, true, '2026-06-03 23:07:05', '2026-06-03 23:07:05');
INSERT INTO public.usuarios (usuario_id, cedula, contrasena, nombre, apellido, correo, telefono, rol_id, foto_perfil, activo, creado_en, actualizado_en) VALUES (11, '0944556677', '$2b$12$N1z3kpDufIcmwp7xTnt.u.ufRsPGZ7cJDBU1VXpZR/N1nsTpSIK.e', 'Pedro José', 'Castro Mendoza', 'pedro.castro@ug.edu.ec', '099000011', 1, NULL, true, '2026-06-03 23:07:05', '2026-06-03 23:07:05');
INSERT INTO public.usuarios (usuario_id, cedula, contrasena, nombre, apellido, correo, telefono, rol_id, foto_perfil, activo, creado_en, actualizado_en) VALUES (2, '0900000002', '$2b$12$N1z3kpDufIcmwp7xTnt.u.ufRsPGZ7cJDBU1VXpZR/N1nsTpSIK.e', 'Juan', 'Perez', 'juan@ug.edu.ec', '099000012', 3, NULL, true, '2026-06-03 23:07:05', '2026-06-05 14:14:45');
INSERT INTO public.usuarios (usuario_id, cedula, contrasena, nombre, apellido, correo, telefono, rol_id, foto_perfil, activo, creado_en, actualizado_en) VALUES (17, '0990171100', '$2b$12$N1z3kpDufIcmwp7xTnt.u.ufRsPGZ7cJDBU1VXpZR/N1nsTpSIK.e', 'Luis', 'Fernandez', 'rrhh@globalsystems.com', '099000017', 2, NULL, false, '2026-06-03 23:07:05', '2026-06-10 15:05:03');
INSERT INTO public.usuarios (usuario_id, cedula, contrasena, nombre, apellido, correo, telefono, rol_id, foto_perfil, activo, creado_en, actualizado_en) VALUES (15, '0990151100', '$2b$12$N1z3kpDufIcmwp7xTnt.u.ufRsPGZ7cJDBU1VXpZR/N1nsTpSIK.e', 'Ana', 'Garcia', 'rrhh@techsolutionsgye.com', '099000015', 2, NULL, true, '2026-06-03 23:07:05', '2026-06-03 23:07:05');
INSERT INTO public.usuarios (usuario_id, cedula, contrasena, nombre, apellido, correo, telefono, rol_id, foto_perfil, activo, creado_en, actualizado_en) VALUES (6, '0942646266', '$2b$12$N1z3kpDufIcmwp7xTnt.u.ufRsPGZ7cJDBU1VXpZR/N1nsTpSIK.e', 'Naldo Jonnel', 'Anchundia Caicedo', 'naldoanchundiac@ug.edu.ec', '0990020956', 1, NULL, true, '2026-06-03 23:07:05', '2026-07-27 14:33:21');
INSERT INTO public.usuarios (usuario_id, cedula, contrasena, nombre, apellido, correo, telefono, rol_id, foto_perfil, activo, creado_en, actualizado_en) VALUES (29, '0990291100', '$2b$12$N1z3kpDufIcmwp7xTnt.u.ufRsPGZ7cJDBU1VXpZR/N1nsTpSIK.e', 'Victor', 'Lino', 'contacto@logisticaavanzada.com', '099000029', 2, NULL, true, '2026-06-03 23:07:05', '2026-06-03 23:07:05');
INSERT INTO public.usuarios (usuario_id, cedula, contrasena, nombre, apellido, correo, telefono, rol_id, foto_perfil, activo, creado_en, actualizado_en) VALUES (30, '0987654321', '$2b$12$6Q6bNdqTZKKXjxPXVgX6z.pUShdd/pHnaRyr.RcInMZJaNbgHVWta', 'Jonnel', 'Anchundia', 'jonnel@ug.edu.ec', '0990020956', 4, NULL, true, '2026-06-10 14:55:59', '2026-06-10 14:55:59');

-- ==========================================
-- DATOS TABLA: public.instituciones
-- ==========================================
INSERT INTO public.instituciones (institucion_id, usuario_id, facultad_id, nombre, nombre_abreviado, ruc, industria, descripcion, sitio_web, direccion, ciudad, correo_contacto, telefono, estado, codigo_convenio, tipo_convenio, fecha_inicio_convenio, fecha_limite_convenio, creado_en, actualizado_en) VALUES (2, 16, 1, 'InnovaSoft Ecuador', 'Empresa de Software Factory', '1234567890002', 'Software Factory', 'Desarrollamos soluciones integrales para el sector tecnológico.', NULL, NULL, 'Guayaquil', 'contacto@innovasoftecuador.com', '0990000002', 'aprobado', 'UG-DFAP-0002-PPP', 'PRÁCTICAS PREPROFESIONALES', '2023-01-01 00:00:00', '2028-12-31 00:00:00', '2026-06-03 23:07:05', '2026-06-03 23:07:05');
INSERT INTO public.instituciones (institucion_id, usuario_id, facultad_id, nombre, nombre_abreviado, ruc, industria, descripcion, sitio_web, direccion, ciudad, correo_contacto, telefono, estado, codigo_convenio, tipo_convenio, fecha_inicio_convenio, fecha_limite_convenio, creado_en, actualizado_en) VALUES (4, 18, 1, 'Cloud Devs', 'Empresa de Cloud Computing', '1234567890004', 'Cloud Computing', 'Desarrollamos soluciones integrales para el sector tecnológico.', NULL, NULL, 'Guayaquil', 'contacto@clouddevs.com', '0990000004', 'aprobado', 'UG-DFAP-0004-PPP', 'PRÁCTICAS PREPROFESIONALES', '2023-01-01 00:00:00', '2028-12-31 00:00:00', '2026-06-03 23:07:05', '2026-06-03 23:07:05');
INSERT INTO public.instituciones (institucion_id, usuario_id, facultad_id, nombre, nombre_abreviado, ruc, industria, descripcion, sitio_web, direccion, ciudad, correo_contacto, telefono, estado, codigo_convenio, tipo_convenio, fecha_inicio_convenio, fecha_limite_convenio, creado_en, actualizado_en) VALUES (5, 19, 1, 'App Works', 'Empresa de Desarrollo Móvil', '1234567890005', 'Desarrollo Móvil', 'Desarrollamos soluciones integrales para el sector tecnológico.', NULL, NULL, 'Guayaquil', 'contacto@appworks.com', '0990000005', 'aprobado', 'UG-DFAP-0005-PPP', 'PRÁCTICAS PREPROFESIONALES', '2023-01-01 00:00:00', '2028-12-31 00:00:00', '2026-06-03 23:07:05', '2026-06-03 23:07:05');
INSERT INTO public.instituciones (institucion_id, usuario_id, facultad_id, nombre, nombre_abreviado, ruc, industria, descripcion, sitio_web, direccion, ciudad, correo_contacto, telefono, estado, codigo_convenio, tipo_convenio, fecha_inicio_convenio, fecha_limite_convenio, creado_en, actualizado_en) VALUES (6, 20, 1, 'Fintech Solutions', 'Empresa de Fintech', '1234567890006', 'Fintech', 'Desarrollamos soluciones integrales para el sector tecnológico.', NULL, NULL, 'Guayaquil', 'contacto@fintechsolutions.com', '0990000006', 'aprobado', 'UG-DFAP-0006-PPP', 'PRÁCTICAS PREPROFESIONALES', '2023-01-01 00:00:00', '2028-12-31 00:00:00', '2026-06-03 23:07:05', '2026-06-03 23:07:05');
INSERT INTO public.instituciones (institucion_id, usuario_id, facultad_id, nombre, nombre_abreviado, ruc, industria, descripcion, sitio_web, direccion, ciudad, correo_contacto, telefono, estado, codigo_convenio, tipo_convenio, fecha_inicio_convenio, fecha_limite_convenio, creado_en, actualizado_en) VALUES (7, 21, 1, 'CyberSec EC', 'Empresa de Ciberseguridad', '1234567890007', 'Ciberseguridad', 'Desarrollamos soluciones integrales para el sector tecnológico.', NULL, NULL, 'Guayaquil', 'contacto@cybersecec.com', '0990000007', 'aprobado', 'UG-DFAP-0007-PPP', 'PRÁCTICAS PREPROFESIONALES', '2023-01-01 00:00:00', '2028-12-31 00:00:00', '2026-06-03 23:07:05', '2026-06-03 23:07:05');
INSERT INTO public.instituciones (institucion_id, usuario_id, facultad_id, nombre, nombre_abreviado, ruc, industria, descripcion, sitio_web, direccion, ciudad, correo_contacto, telefono, estado, codigo_convenio, tipo_convenio, fecha_inicio_convenio, fecha_limite_convenio, creado_en, actualizado_en) VALUES (8, 22, 1, 'Smart Code', 'Empresa de Desarrollo Web', '1234567890008', 'Desarrollo Web', 'Desarrollamos soluciones integrales para el sector tecnológico.', NULL, NULL, 'Guayaquil', 'contacto@smartcode.com', '0990000008', 'aprobado', 'UG-DFAP-0008-PPP', 'PRÁCTICAS PREPROFESIONALES', '2023-01-01 00:00:00', '2028-12-31 00:00:00', '2026-06-03 23:07:05', '2026-06-03 23:07:05');
INSERT INTO public.instituciones (institucion_id, usuario_id, facultad_id, nombre, nombre_abreviado, ruc, industria, descripcion, sitio_web, direccion, ciudad, correo_contacto, telefono, estado, codigo_convenio, tipo_convenio, fecha_inicio_convenio, fecha_limite_convenio, creado_en, actualizado_en) VALUES (9, 23, 1, 'Nexus Tech', 'Empresa de Sistemas Empresariales', '1234567890009', 'Sistemas Empresariales', 'Desarrollamos soluciones integrales para el sector tecnológico.', NULL, NULL, 'Guayaquil', 'contacto@nexustech.com', '0990000009', 'aprobado', 'UG-DFAP-0009-PPP', 'PRÁCTICAS PREPROFESIONALES', '2023-01-01 00:00:00', '2028-12-31 00:00:00', '2026-06-03 23:07:05', '2026-06-03 23:07:05');
INSERT INTO public.instituciones (institucion_id, usuario_id, facultad_id, nombre, nombre_abreviado, ruc, industria, descripcion, sitio_web, direccion, ciudad, correo_contacto, telefono, estado, codigo_convenio, tipo_convenio, fecha_inicio_convenio, fecha_limite_convenio, creado_en, actualizado_en) VALUES (10, 24, 1, 'Dev Masters', 'Empresa de Desarrollo Backend', '12345678900010', 'Desarrollo Backend', 'Desarrollamos soluciones integrales para el sector tecnológico.', NULL, NULL, 'Guayaquil', 'contacto@devmasters.com', '0990000010', 'aprobado', 'UG-DFAP-0010-PPP', 'PRÁCTICAS PREPROFESIONALES', '2023-01-01 00:00:00', '2028-12-31 00:00:00', '2026-06-03 23:07:05', '2026-06-03 23:07:05');
INSERT INTO public.instituciones (institucion_id, usuario_id, facultad_id, nombre, nombre_abreviado, ruc, industria, descripcion, sitio_web, direccion, ciudad, correo_contacto, telefono, estado, codigo_convenio, tipo_convenio, fecha_inicio_convenio, fecha_limite_convenio, creado_en, actualizado_en) VALUES (11, 25, 1, 'DataMind GYE', 'Empresa de Data Science', '12345678900011', 'Data Science', 'Especialistas en análisis de grandes volúmenes de datos.', NULL, NULL, 'Guayaquil', 'contacto@datamindgye.com', '0990000011', 'aprobado', 'UG-DFAP-0011-PPP', 'PRÁCTICAS PREPROFESIONALES', '2023-05-15 00:00:00', '2028-05-15 00:00:00', '2026-06-03 23:07:05', '2026-06-03 23:07:05');
INSERT INTO public.instituciones (institucion_id, usuario_id, facultad_id, nombre, nombre_abreviado, ruc, industria, descripcion, sitio_web, direccion, ciudad, correo_contacto, telefono, estado, codigo_convenio, tipo_convenio, fecha_inicio_convenio, fecha_limite_convenio, creado_en, actualizado_en) VALUES (12, 26, 1, 'AI Vision', 'Empresa de Inteligencia Artificial', '12345678900012', 'Inteligencia Artificial', 'Especialistas en análisis de grandes volúmenes de datos.', NULL, NULL, 'Guayaquil', 'contacto@aivision.com', '0990000012', 'aprobado', 'UG-DFAP-0012-PPP', 'PRÁCTICAS PREPROFESIONALES', '2023-05-15 00:00:00', '2028-05-15 00:00:00', '2026-06-03 23:07:05', '2026-06-03 23:07:05');
INSERT INTO public.instituciones (institucion_id, usuario_id, facultad_id, nombre, nombre_abreviado, ruc, industria, descripcion, sitio_web, direccion, ciudad, correo_contacto, telefono, estado, codigo_convenio, tipo_convenio, fecha_inicio_convenio, fecha_limite_convenio, creado_en, actualizado_en) VALUES (13, 27, 1, 'Metricas EC', 'Empresa de Big Data', '12345678900013', 'Big Data', 'Especialistas en análisis de grandes volúmenes de datos.', NULL, NULL, 'Guayaquil', 'contacto@metricasec.com', '0990000013', 'aprobado', 'UG-DFAP-0013-PPP', 'PRÁCTICAS PREPROFESIONALES', '2023-05-15 00:00:00', '2028-05-15 00:00:00', '2026-06-03 23:07:05', '2026-06-03 23:07:05');
INSERT INTO public.instituciones (institucion_id, usuario_id, facultad_id, nombre, nombre_abreviado, ruc, industria, descripcion, sitio_web, direccion, ciudad, correo_contacto, telefono, estado, codigo_convenio, tipo_convenio, fecha_inicio_convenio, fecha_limite_convenio, creado_en, actualizado_en) VALUES (14, 28, 2, 'InduProducción S.A.', 'Empresa de Manufactura', '12345678900014', 'Manufactura', 'Líderes en procesos industriales y logística a nivel nacional.', NULL, NULL, 'Guayaquil', 'contacto@induproduccións.a..com', '0990000014', 'aprobado', 'UG-DFAP-0014-PPP', 'PRÁCTICAS PREPROFESIONALES', '2024-02-10 00:00:00', '2029-02-10 00:00:00', '2026-06-03 23:07:05', '2026-06-03 23:07:05');
INSERT INTO public.instituciones (institucion_id, usuario_id, facultad_id, nombre, nombre_abreviado, ruc, industria, descripcion, sitio_web, direccion, ciudad, correo_contacto, telefono, estado, codigo_convenio, tipo_convenio, fecha_inicio_convenio, fecha_limite_convenio, creado_en, actualizado_en) VALUES (15, 29, 2, 'Logística Avanzada', 'Empresa de Logística Industrial', '12345678900015', 'Logística Industrial', 'Líderes en procesos industriales y logística a nivel nacional.', NULL, NULL, 'Guayaquil', 'contacto@logísticaavanzada.com', '0990000015', 'aprobado', 'UG-DFAP-0015-PPP', 'PRÁCTICAS PREPROFESIONALES', '2024-02-10 00:00:00', '2029-02-10 00:00:00', '2026-06-03 23:07:05', '2026-06-03 23:07:05');
INSERT INTO public.instituciones (institucion_id, usuario_id, facultad_id, nombre, nombre_abreviado, ruc, industria, descripcion, sitio_web, direccion, ciudad, correo_contacto, telefono, estado, codigo_convenio, tipo_convenio, fecha_inicio_convenio, fecha_limite_convenio, creado_en, actualizado_en) VALUES (3, 17, 1, 'Global Systems', 'Empresa de Consultoría IT', '1234567890003', 'Consultoría IT', 'Desarrollamos soluciones integrales para el sector tecnológico.', NULL, NULL, 'Guayaquil', 'contacto@globalsystems.com', '0990000003', 'aprobado', 'UG-DFAP-0003-PPP', 'PRÁCTICAS PREPROFESIONALES', '2023-01-01 00:00:00', '2028-12-29 00:00:00', '2026-06-03 23:07:05', '2026-06-10 15:05:02');
INSERT INTO public.instituciones (institucion_id, usuario_id, facultad_id, nombre, nombre_abreviado, ruc, industria, descripcion, sitio_web, direccion, ciudad, correo_contacto, telefono, estado, codigo_convenio, tipo_convenio, fecha_inicio_convenio, fecha_limite_convenio, creado_en, actualizado_en) VALUES (1, 15, 1, 'Tech Solutions GYE', 'Empresa de Desarrollo Web', '1234567890001', 'Desarrollo Web', 'Desarrollamos soluciones integrales para el sector tecnológico.', 'www.ts.com', 'calle 10 de agosto', 'Guayaquil', 'contacto@techsolutionsgye.com', '0990000001', 'aprobado', 'UG-DFAP-0001-PPP', 'PRÁCTICAS PREPROFESIONALES', '2023-01-01 00:00:00', '2028-12-31 00:00:00', '2026-06-03 23:07:05', '2026-06-10 15:38:34');

-- ==========================================
-- DATOS TABLA: public.supervisores
-- ==========================================
INSERT INTO public.supervisores (supervisor_id, institucion_id, tipo_identificacion, numero_identificacion, nombre, apellido, correo, departamento, cargo, telefono, observacion, activo, creado_en, actualizado_en) VALUES (1, 1, 'Cedula', '0999999901', 'Supervisor 1', 'Apellido 1', 'sup1@empresa.com', 'Recursos Humanos', 'Gerente de RRHH', '0990001101', NULL, true, '2026-06-03 23:07:05', '2026-06-03 23:07:05');
INSERT INTO public.supervisores (supervisor_id, institucion_id, tipo_identificacion, numero_identificacion, nombre, apellido, correo, departamento, cargo, telefono, observacion, activo, creado_en, actualizado_en) VALUES (3, 3, 'Cedula', '0999999903', 'Supervisor 3', 'Apellido 3', 'sup3@empresa.com', 'Recursos Humanos', 'Gerente de RRHH', '0990001103', NULL, true, '2026-06-03 23:07:05', '2026-06-03 23:07:05');
INSERT INTO public.supervisores (supervisor_id, institucion_id, tipo_identificacion, numero_identificacion, nombre, apellido, correo, departamento, cargo, telefono, observacion, activo, creado_en, actualizado_en) VALUES (4, 4, 'Cedula', '0999999904', 'Supervisor 4', 'Apellido 4', 'sup4@empresa.com', 'Recursos Humanos', 'Gerente de RRHH', '0990001104', NULL, true, '2026-06-03 23:07:05', '2026-06-03 23:07:05');
INSERT INTO public.supervisores (supervisor_id, institucion_id, tipo_identificacion, numero_identificacion, nombre, apellido, correo, departamento, cargo, telefono, observacion, activo, creado_en, actualizado_en) VALUES (5, 5, 'Cedula', '0999999905', 'Supervisor 5', 'Apellido 5', 'sup5@empresa.com', 'Recursos Humanos', 'Gerente de RRHH', '0990001105', NULL, true, '2026-06-03 23:07:05', '2026-06-03 23:07:05');
INSERT INTO public.supervisores (supervisor_id, institucion_id, tipo_identificacion, numero_identificacion, nombre, apellido, correo, departamento, cargo, telefono, observacion, activo, creado_en, actualizado_en) VALUES (6, 6, 'Cedula', '0999999906', 'Supervisor 6', 'Apellido 6', 'sup6@empresa.com', 'Recursos Humanos', 'Gerente de RRHH', '0990001106', NULL, true, '2026-06-03 23:07:05', '2026-06-03 23:07:05');
INSERT INTO public.supervisores (supervisor_id, institucion_id, tipo_identificacion, numero_identificacion, nombre, apellido, correo, departamento, cargo, telefono, observacion, activo, creado_en, actualizado_en) VALUES (7, 7, 'Cedula', '0999999907', 'Supervisor 7', 'Apellido 7', 'sup7@empresa.com', 'Recursos Humanos', 'Gerente de RRHH', '0990001107', NULL, true, '2026-06-03 23:07:05', '2026-06-03 23:07:05');
INSERT INTO public.supervisores (supervisor_id, institucion_id, tipo_identificacion, numero_identificacion, nombre, apellido, correo, departamento, cargo, telefono, observacion, activo, creado_en, actualizado_en) VALUES (8, 8, 'Cedula', '0999999908', 'Supervisor 8', 'Apellido 8', 'sup8@empresa.com', 'Recursos Humanos', 'Gerente de RRHH', '0990001108', NULL, true, '2026-06-03 23:07:05', '2026-06-03 23:07:05');
INSERT INTO public.supervisores (supervisor_id, institucion_id, tipo_identificacion, numero_identificacion, nombre, apellido, correo, departamento, cargo, telefono, observacion, activo, creado_en, actualizado_en) VALUES (9, 9, 'Cedula', '0999999909', 'Supervisor 9', 'Apellido 9', 'sup9@empresa.com', 'Recursos Humanos', 'Gerente de RRHH', '0990001109', NULL, true, '2026-06-03 23:07:05', '2026-06-03 23:07:05');
INSERT INTO public.supervisores (supervisor_id, institucion_id, tipo_identificacion, numero_identificacion, nombre, apellido, correo, departamento, cargo, telefono, observacion, activo, creado_en, actualizado_en) VALUES (10, 10, 'Cedula', '0999999910', 'Supervisor 10', 'Apellido 10', 'sup10@empresa.com', 'Recursos Humanos', 'Gerente de RRHH', '0990001110', NULL, true, '2026-06-03 23:07:05', '2026-06-03 23:07:05');
INSERT INTO public.supervisores (supervisor_id, institucion_id, tipo_identificacion, numero_identificacion, nombre, apellido, correo, departamento, cargo, telefono, observacion, activo, creado_en, actualizado_en) VALUES (11, 11, 'Cedula', '0999999911', 'Supervisor 11', 'Apellido 11', 'sup11@empresa.com', 'Recursos Humanos', 'Gerente de RRHH', '0990001111', NULL, true, '2026-06-03 23:07:05', '2026-06-03 23:07:05');
INSERT INTO public.supervisores (supervisor_id, institucion_id, tipo_identificacion, numero_identificacion, nombre, apellido, correo, departamento, cargo, telefono, observacion, activo, creado_en, actualizado_en) VALUES (12, 12, 'Cedula', '0999999912', 'Supervisor 12', 'Apellido 12', 'sup12@empresa.com', 'Recursos Humanos', 'Gerente de RRHH', '0990001112', NULL, true, '2026-06-03 23:07:05', '2026-06-03 23:07:05');
INSERT INTO public.supervisores (supervisor_id, institucion_id, tipo_identificacion, numero_identificacion, nombre, apellido, correo, departamento, cargo, telefono, observacion, activo, creado_en, actualizado_en) VALUES (13, 13, 'Cedula', '0999999913', 'Supervisor 13', 'Apellido 13', 'sup13@empresa.com', 'Recursos Humanos', 'Gerente de RRHH', '0990001113', NULL, true, '2026-06-03 23:07:05', '2026-06-03 23:07:05');
INSERT INTO public.supervisores (supervisor_id, institucion_id, tipo_identificacion, numero_identificacion, nombre, apellido, correo, departamento, cargo, telefono, observacion, activo, creado_en, actualizado_en) VALUES (14, 14, 'Cedula', '0999999914', 'Supervisor 14', 'Apellido 14', 'sup14@empresa.com', 'Recursos Humanos', 'Gerente de RRHH', '0990001114', NULL, true, '2026-06-03 23:07:05', '2026-06-03 23:07:05');
INSERT INTO public.supervisores (supervisor_id, institucion_id, tipo_identificacion, numero_identificacion, nombre, apellido, correo, departamento, cargo, telefono, observacion, activo, creado_en, actualizado_en) VALUES (15, 15, 'Cedula', '0999999915', 'Supervisor 15', 'Apellido 15', 'sup15@empresa.com', 'Recursos Humanos', 'Gerente de RRHH', '0990001115', NULL, true, '2026-06-03 23:07:05', '2026-06-03 23:07:05');
INSERT INTO public.supervisores (supervisor_id, institucion_id, tipo_identificacion, numero_identificacion, nombre, apellido, correo, departamento, cargo, telefono, observacion, activo, creado_en, actualizado_en) VALUES (16, 1, 'Cedula', '33123123', 'juan', 'acasyt', 'dasdasdasd', 'asdasdasd', 'asdasa', '34535345', NULL, false, '2026-06-10 14:58:25', '2026-06-10 14:58:25');
INSERT INTO public.supervisores (supervisor_id, institucion_id, tipo_identificacion, numero_identificacion, nombre, apellido, correo, departamento, cargo, telefono, observacion, activo, creado_en, actualizado_en) VALUES (17, 2, 'Cedula', '098787678', 'Juan Pablo', 'Castro Bajaña', 'juanpablo@invo.com', 'sistemas', 'gerente sistemas', '0989890989', NULL, true, '2026-07-12 21:45:39', '2026-07-12 21:45:39');
INSERT INTO public.supervisores (supervisor_id, institucion_id, tipo_identificacion, numero_identificacion, nombre, apellido, correo, departamento, cargo, telefono, observacion, activo, creado_en, actualizado_en) VALUES (2, 2, 'Cedula', '0999999902', 'Pedro Luis', 'Castillo Mora', 'predro@empresa.com', 'Recursos Humanos', 'Gerente de RRHH', '0990001102', NULL, false, '2026-06-03 23:07:05', '2026-06-03 23:07:05');

-- ==========================================
-- DATOS TABLA: public.perfiles_estudiante
-- ==========================================
INSERT INTO public.perfiles_estudiante (perfil_id, usuario_id, carrera_id, facultad_id, semestre, universidad, resumen_experiencia, intereses, curriculum_url, creado_en, actualizado_en, calculando_nlp) VALUES (3, 7, 1, 1, '8', 'Universidad de Guayaquil', 'Desarrollador web con experiencia en proyectos académicos usando MERN stack. Creador de sistema de inventario para pyme local.', 'Me interesa el desarrollo Backend y la arquitectura de software.', NULL, '2026-06-03 23:07:05', '2026-06-03 23:07:05', false);
INSERT INTO public.perfiles_estudiante (perfil_id, usuario_id, carrera_id, facultad_id, semestre, universidad, resumen_experiencia, intereses, curriculum_url, creado_en, actualizado_en, calculando_nlp) VALUES (4, 8, 1, 1, '8', 'Universidad de Guayaquil', 'Desarrollador web con experiencia en proyectos académicos usando MERN stack. Creador de sistema de inventario para pyme local.', 'Me interesa el desarrollo Backend y la arquitectura de software.', NULL, '2026-06-03 23:07:05', '2026-06-03 23:07:05', false);
INSERT INTO public.perfiles_estudiante (perfil_id, usuario_id, carrera_id, facultad_id, semestre, universidad, resumen_experiencia, intereses, curriculum_url, creado_en, actualizado_en, calculando_nlp) VALUES (5, 9, 1, 1, '8', 'Universidad de Guayaquil', 'Desarrollador web con experiencia en proyectos académicos usando MERN stack. Creador de sistema de inventario para pyme local.', 'Me interesa el desarrollo Backend y la arquitectura de software.', NULL, '2026-06-03 23:07:05', '2026-06-03 23:07:05', false);
INSERT INTO public.perfiles_estudiante (perfil_id, usuario_id, carrera_id, facultad_id, semestre, universidad, resumen_experiencia, intereses, curriculum_url, creado_en, actualizado_en, calculando_nlp) VALUES (6, 10, 2, 1, '7', 'Universidad de Guayaquil', 'Entusiasta de los datos. He participado en hackathons de análisis predictivo. Manejo de Python, Pandas y Scikit-Learn.', 'Inteligencia Artificial, Machine Learning, Análisis predictivo.', NULL, '2026-06-03 23:07:05', '2026-06-03 23:07:05', false);
INSERT INTO public.perfiles_estudiante (perfil_id, usuario_id, carrera_id, facultad_id, semestre, universidad, resumen_experiencia, intereses, curriculum_url, creado_en, actualizado_en, calculando_nlp) VALUES (8, 12, 3, 2, '8', 'Universidad de Guayaquil', 'Experiencia teórica y práctica en optimización de procesos mediante simuladores. Conocimiento en Lean Manufacturing.', 'Gestión de calidad, Mejora continua, Logística.', NULL, '2026-06-03 23:07:05', '2026-06-03 23:07:05', false);
INSERT INTO public.perfiles_estudiante (perfil_id, usuario_id, carrera_id, facultad_id, semestre, universidad, resumen_experiencia, intereses, curriculum_url, creado_en, actualizado_en, calculando_nlp) VALUES (9, 13, 3, 2, '8', 'Universidad de Guayaquil', 'Experiencia teórica y práctica en optimización de procesos mediante simuladores. Conocimiento en Lean Manufacturing.', 'Gestión de calidad, Mejora continua, Logística.', NULL, '2026-06-03 23:07:05', '2026-06-03 23:07:05', false);
INSERT INTO public.perfiles_estudiante (perfil_id, usuario_id, carrera_id, facultad_id, semestre, universidad, resumen_experiencia, intereses, curriculum_url, creado_en, actualizado_en, calculando_nlp) VALUES (10, 14, 3, 2, '8', 'Universidad de Guayaquil', 'Experiencia teórica y práctica en optimización de procesos mediante simuladores. Conocimiento en Lean Manufacturing.', 'Gestión de calidad, Mejora continua, Logística.', NULL, '2026-06-03 23:07:05', '2026-06-03 23:07:05', false);
INSERT INTO public.perfiles_estudiante (perfil_id, usuario_id, carrera_id, facultad_id, semestre, universidad, resumen_experiencia, intereses, curriculum_url, creado_en, actualizado_en, calculando_nlp) VALUES (2, 6, 1, 1, '9', 'Universidad de Guayaquil', E'Cuento con experiencia en la creación y mejora de aplicaciones web, con un fuerte enfoque en la implementación de interfaces gráficas, corrección de errores y el desarrollo de nuevas funcionalidades utilizando React, HTML, CSS y JavaScript. Manejo el control de versiones con Git y GitHub, y tengo conocimientos prácticos en el consumo de APIs REST y manejo de angular experimentado, me especializo en backend, se SQL y tambien se trabajr en node.js, tabaje en sistemas POO y buen analista\n\n.', 'Desarrollo Web, Ciencia de Datos, backend, IA', NULL, '2026-06-03 23:07:05', '2026-07-27 14:33:21', false);
INSERT INTO public.perfiles_estudiante (perfil_id, usuario_id, carrera_id, facultad_id, semestre, universidad, resumen_experiencia, intereses, curriculum_url, creado_en, actualizado_en, calculando_nlp) VALUES (1, 5, 1, 1, '9', 'Universidad de Guayaquil', 'Me especializo en el análisis profundo de información y la creación de sistemas inteligentes. Además de mi enfoque en algoritmos de aprendizaje automático, cuento con vasta experiencia en desarrollo de aplicaciones móviles multiplataforma usando Flutter, así como diseño de interfaces frontend con React y Tailwind CSS. ademas manejo agnetes de IA en diferentes modelos, con portocolos MCP y python ', 'Redes neuronales, Análisis estadístico, Desarrollo Frontend', NULL, '2026-06-03 23:07:05', '2026-06-24 00:13:06', false);
INSERT INTO public.perfiles_estudiante (perfil_id, usuario_id, carrera_id, facultad_id, semestre, universidad, resumen_experiencia, intereses, curriculum_url, creado_en, actualizado_en, calculando_nlp) VALUES (7, 11, 2, 1, '9', 'Universidad de Guayaquil', 'Entusiasta de los datos. He participado en hackathons de análisis predictivo. Manejo de Python, Pandas y Scikit-Learn.', 'Inteligencia Artificial, Machine Learning, Análisis predictivo.', NULL, '2026-06-03 23:07:05', '2026-06-03 23:07:05', false);

-- ==========================================
-- DATOS TABLA: public.perfiles_gestor
-- ==========================================
INSERT INTO public.perfiles_gestor (perfil_id, usuario_id, facultad_id, carrera_id, creado_en, actualizado_en) VALUES (3, 4, 2, 3, '2026-06-03 23:07:05', '2026-06-03 23:07:05');
INSERT INTO public.perfiles_gestor (perfil_id, usuario_id, facultad_id, carrera_id, creado_en, actualizado_en) VALUES (1, 2, 1, 1, '2026-06-03 23:07:05', '2026-06-03 23:07:05');
INSERT INTO public.perfiles_gestor (perfil_id, usuario_id, facultad_id, carrera_id, creado_en, actualizado_en) VALUES (2, 3, 1, 2, '2026-06-03 23:07:05', '2026-06-03 23:07:05');

-- ==========================================
-- DATOS TABLA: public.vacantes
-- ==========================================
INSERT INTO public.vacantes (vacante_id, institucion_id, supervisor_id, titulo, area, descripcion, requisitos, modalidad, ubicacion, total_horas, horas_diarias, horario, cupos, activo, fecha_expiracion, creado_en, actualizado_en) VALUES (26, 1, 1, 'Desarrollo de Software Móvil y Servicios Web', 'Desarrollo Móvil', 'Participación en la construcción de soluciones para dispositivos celulares y tablets. Las actividades principales involucran el consumo de APIs, la estructuración de interfaces de usuario ágiles y la persistencia de información en sistemas relacionales del lado del servidor.', 'Se requiere destreza armando pantallas interactivas multiplataforma. Nociones sólidas en la creación de endpoints y administración de tablas de datos. Interés por la experiencia de usuario (UX) y el rendimiento en la nube.', 'Híbrido', 'Guayaquil', 144, 6, 'Lunes a Viernes', 1, false, '2026-07-11 00:00:00', '2026-06-20 10:45:04', '2026-06-22 00:04:03');
INSERT INTO public.vacantes (vacante_id, institucion_id, supervisor_id, titulo, area, descripcion, requisitos, modalidad, ubicacion, total_horas, horas_diarias, horario, cupos, activo, fecha_expiracion, creado_en, actualizado_en) VALUES (18, 2, 2, 'Data Scientist / Ingeniero Machine Learning', 'Tecnología', 'Buscamos un estudiante de la carrera de Software con interés en Ciencia de Datos, Machine Learning e Inteligencia Artificial para apoyar en el desarrollo de proyectos de análisis de datos y modelos predictivos. El candidato participará en el procesamiento, limpieza y análisis de grandes volúmenes de información utilizando Python, Pandas y Scikit-Learn, contribuyendo a la optimización de procesos mediante soluciones basadas en datos. Se valorará la capacidad analítica, el aprendizaje continuo y el interés por desarrollar modelos de machine learning aplicados a problemas reales.', E'Estudiante de la carrera de Software.\nConocimientos en Inteligencia Artificial.\nConocimientos en Machine Learning.\nConocimientos en Ciencia de Datos (Data Science).\nManejo de Python.\nExperiencia académica utilizando Pandas.\nConocimientos en Scikit-Learn.\nConocimientos en análisis y procesamiento de datos.\nInterés en el desarrollo de modelos predictivos.\nCapacidad analítica para la optimización de procesos.', 'Remoto', 'Guayaquil', 240, 6, 'Matutino', 2, true, '2026-07-17 00:00:00', '2026-06-11 23:51:57', '2026-07-09 00:16:23');
INSERT INTO public.vacantes (vacante_id, institucion_id, supervisor_id, titulo, area, descripcion, requisitos, modalidad, ubicacion, total_horas, horas_diarias, horario, cupos, activo, fecha_expiracion, creado_en, actualizado_en) VALUES (10, 10, 10, 'Asistente de Desarrollo Frontend', 'Desarrollo web', 'Buscamos un estudiante con interés en el desarrollo web para apoyar al equipo en la creación y mejora de aplicaciones internas en frontend. Durante las prácticas participará en tareas de implementación de interfaces, corrección de errores y desarrollo de nuevas funcionalidades, trabajando junto a desarrolladores con experiencia.', E'- Conocimientos básicos de HTML, CSS y JavaScript.\n- Experiencia académica utilizando React.\n- Manejo básico de Git y GitHub.\n- Conocimientos de consumo de APIs REST.\n- Capacidad para trabajar en equipo y disposición para aprender.\n- Conocimiento en angular.', 'Presencial', 'Daule', 144, 5, 'Lunes a Viernes', 10, true, '2026-09-19 00:00:00', '2026-06-03 23:07:05', '2026-07-21 13:27:51');
INSERT INTO public.vacantes (vacante_id, institucion_id, supervisor_id, titulo, area, descripcion, requisitos, modalidad, ubicacion, total_horas, horas_diarias, horario, cupos, activo, fecha_expiracion, creado_en, actualizado_en) VALUES (1, 1, 1, 'Desarrollador Backend Python & Microservicios', 'Tecnología y Software', 'Buscamos un practicante apasionado por el desarrollo backend en Python para colaborar en la construcción de microservicios escalables con Flask/FastAPI, integración de APIs RESTful y optimización de consultas SQL en PostgreSQL.', E'- Estudiante de 6to semestre en adelante de Ing. en Software o Sistemas.\n- Manejo fluido de Python y principios de Programación Orientada a Objetos.\n- Conocimiento en diseño de API REST y manejo de Git.\n- Deseable experiencia básica con Flask o Django.', 'Híbrido', 'Guayaquil', 240, 6, 'Lunes a Viernes 08:00 a 14:00', 2, true, '2027-12-31 00:00:00', '2026-06-03 23:07:05', '2026-06-03 23:07:05');
INSERT INTO public.vacantes (vacante_id, institucion_id, supervisor_id, titulo, area, descripcion, requisitos, modalidad, ubicacion, total_horas, horas_diarias, horario, cupos, activo, fecha_expiracion, creado_en, actualizado_en) VALUES (2, 2, 2, 'Desarrollador Java & Arquitectura Enterprise', 'Desarrollo de Software', 'Únete al equipo de desarrollo institucional para participar en la modernización de plataformas empresariales construidas sobre Java Spring Boot. Trabajarás con patrones de diseño, pruebas unitarias y gestión de bases de datos relacionales.', E'- Estudiante de últimos semestres de Ing. en Software o Ciencias de la Computación.\n- Sólidas bases de arquitectura Java (Spring Boot / Maven / Gradle).\n- Experiencia en bases de datos relacionales y sentencias SQL complejas.\n- Buenas prácticas de código limpio y control de versiones.', 'Presencial', 'Guayaquil', 240, 6, 'Lunes a Viernes 08:30 a 14:30', 2, true, '2027-12-31 00:00:00', '2026-06-03 23:07:05', '2026-06-03 23:07:05');
INSERT INTO public.vacantes (vacante_id, institucion_id, supervisor_id, titulo, area, descripcion, requisitos, modalidad, ubicacion, total_horas, horas_diarias, horario, cupos, activo, fecha_expiracion, creado_en, actualizado_en) VALUES (3, 3, 3, 'Desarrollador Node.js & Servicios en la Nube', 'Desarrollo Web & Cloud', 'Oportunidad de práctica para desarrolladores con interés en JavaScript/TypeScript backend. Participarás en la creación de APIs asíncronas de alto rendimiento con Node.js/Express e integración con servicios cloud.', E'- Estudiante universitario de Software, Sistemas o carreras afines.\n- Dominio de JavaScript / TypeScript moderno (ES6+).\n- Conocimientos de Node.js, Express y conexión a bases de datos NoSQL/SQL.\n- Interés en entornos cloud (AWS o Google Cloud).', 'Remoto', 'Guayaquil', 240, 6, 'Lunes a Viernes 09:00 a 15:00', 3, true, '2027-12-31 00:00:00', '2026-06-03 23:07:05', '2026-06-03 23:07:05');
INSERT INTO public.vacantes (vacante_id, institucion_id, supervisor_id, titulo, area, descripcion, requisitos, modalidad, ubicacion, total_horas, horas_diarias, horario, cupos, activo, fecha_expiracion, creado_en, actualizado_en) VALUES (7, 7, 7, 'Desarrollador Full Stack (Énfasis en Backend)', 'Desarrollo Web', 'Apoyo en el desarrollo integral de aplicaciones corporativas. Diseñarás lógica de servidor segura e integrarás componentes frontend dinámicos con React y servicios API REST.', E'- Estudiante de 7mo semestre en adelante de Ing. en Software.\n- Manejo de JavaScript / TypeScript tanto en cliente como en servidor.\n- Experiencia básica en React/Vue y Node.js/Python.\n- Manejo de Git y herramientas de testing.', 'Híbrido', 'Guayaquil', 240, 6, 'Lunes a Viernes 08:00 a 14:00', 2, true, '2027-12-31 00:00:00', '2026-06-03 23:07:05', '2026-06-03 23:07:05');
INSERT INTO public.vacantes (vacante_id, institucion_id, supervisor_id, titulo, area, descripcion, requisitos, modalidad, ubicacion, total_horas, horas_diarias, horario, cupos, activo, fecha_expiracion, creado_en, actualizado_en) VALUES (4, 4, 4, 'Desarrollador C# .NET Core & Servicios Web', 'Desarrollo Backend', 'Buscamos estudiante interesado en la plataforma Microsoft .NET Core. Te integrarás en proyectos corporativos para desarrollar Web APIs, conectar modelos ORM (Entity Framework) y aplicar pruebas de integración.', E'- Conocimiento en lenguajes C# y sintaxis de .NET Framework / Core.\n- Manejo de Entity Framework o controladores SQL Server / PostgreSQL.\n- Comprensión de conceptos de POO y capas de software.\n- Capacidad de trabajo colaborativo en equipos ágiles.', 'Híbrido', 'Guayaquil', 240, 6, 'Lunes a Viernes 08:00 a 14:00', 2, true, '2027-12-31 00:00:00', '2026-06-03 23:07:05', '2026-06-03 23:07:05');
INSERT INTO public.vacantes (vacante_id, institucion_id, supervisor_id, titulo, area, descripcion, requisitos, modalidad, ubicacion, total_horas, horas_diarias, horario, cupos, activo, fecha_expiracion, creado_en, actualizado_en) VALUES (17, 1, 1, 'Análisis de Datos y Desarrollo Web', 'Sistemas', 'Buscamos un estudiante de Ingeniería en Software o carreras afines para apoyar en el análisis de datos y el desarrollo de soluciones web internas. El practicante participará en la limpieza y procesamiento de datos, generación de reportes, automatización de tareas mediante scripts y apoyo en el desarrollo de módulos web utilizando tecnologías frontend y backend. Tendrá la oportunidad de trabajar con datos reales y colaborar con equipos multidisciplinarios en proyectos tecnológicos.', E'Requisitos en texto\nEstudiante de Ingeniería en Software, Sistemas o carreras afines (5to semestre en adelante).\nConocimientos de Python para análisis y procesamiento de datos.\nManejo básico de Pandas y NumPy.\nConocimientos de estadística descriptiva.\nConocimientos de JavaScript para desarrollo web.\nCapacidad para interpretar y visualizar información.\nConocimientos básicos de bases de datos relacionales.\nHabilidades de comunicación y trabajo en equipo.\nDeseable experiencia académica en proyectos de análisis de datos o desarrollo web.', 'Remoto', 'Guayaquil', 144, 6, 'Lunes a Viernes', 4, false, '2026-06-28 00:00:00', '2026-06-11 23:02:24', '2026-06-15 21:51:20');
INSERT INTO public.vacantes (vacante_id, institucion_id, supervisor_id, titulo, area, descripcion, requisitos, modalidad, ubicacion, total_horas, horas_diarias, horario, cupos, activo, fecha_expiracion, creado_en, actualizado_en) VALUES (6, 6, 6, 'Desarrollador Go / Golang & Sistemas Concurrentes', 'Software e Infraestructura', 'Buscamos pasante enfocado en rendimiento y sistemas de alta velocidad. Trabajarás con lenguaje Go desarrollando servicios distribuidos, APIs de respuesta ultra rápida y contenedores Docker.', E'- Estudiante de Software o Ciencias de la Computación.\n- Interés o experiencia académica programando en Go (Golang) o C/C++.\n- Nociones de concurrencia (goroutines, channels) y redes TCP/HTTP.\n- Manejo de entornos Linux y Docker.', 'Híbrido', 'Guayaquil', 240, 6, 'Lunes a Viernes 09:00 a 15:00', 2, true, '2027-12-31 00:00:00', '2026-06-03 23:07:05', '2026-06-03 23:07:05');
INSERT INTO public.vacantes (vacante_id, institucion_id, supervisor_id, titulo, area, descripcion, requisitos, modalidad, ubicacion, total_horas, horas_diarias, horario, cupos, activo, fecha_expiracion, creado_en, actualizado_en) VALUES (8, 8, 8, 'Ingeniero Backend & Seguridad de APIs', 'Ciberseguridad y Backend', 'Práctica profesional enfocada en la protección y optimización de endpoints backend. Implementación de protocolos de autenticación (OAuth2, JWT), encriptación y auditoría de peticiones HTTP.', E'- Estudiante de Software, Ciberseguridad o Sistemas.\n- Conocimientos sobre protocolos de seguridad web y JWT/OAuth.\n- Experiencia programando backend en Python, Node.js o Java.\n- Pensamiento lógico enfocado en prevención de vulnerabilidades.', 'Remoto', 'Guayaquil', 240, 6, 'Lunes a Viernes 09:00 a 15:00', 2, true, '2027-12-31 00:00:00', '2026-06-03 23:07:05', '2026-06-03 23:07:05');
INSERT INTO public.vacantes (vacante_id, institucion_id, supervisor_id, titulo, area, descripcion, requisitos, modalidad, ubicacion, total_horas, horas_diarias, horario, cupos, activo, fecha_expiracion, creado_en, actualizado_en) VALUES (11, 11, 11, 'Analista de Business Intelligence (BI) & Reportes', 'Ciencia de Datos & BI', 'Apoyo en el diseño de tableros ejecutivos interactivos utilizando Power BI y SQL. Trabajarás transformando datos crudos en métricas e indicadores de rendimiento claves (KPIs) para la gerencia.', E'- Estudiante de Ciencia de Datos, Software o Ing. Industrial.\n- Dominio de herramientas BI (Power BI, Tableau) y lenguaje DAX.\n- Manejo fluido de SQL y estructuración de modelos dimensionales.\n- Habilidades de comunicación y presentación visual de datos.', 'Remoto', 'Guayaquil', 240, 6, 'Lunes a Viernes 09:00 a 15:00', 2, true, '2027-12-31 00:00:00', '2026-06-03 23:07:05', '2026-06-03 23:07:05');
INSERT INTO public.vacantes (vacante_id, institucion_id, supervisor_id, titulo, area, descripcion, requisitos, modalidad, ubicacion, total_horas, horas_diarias, horario, cupos, activo, fecha_expiracion, creado_en, actualizado_en) VALUES (12, 12, 12, 'Analista de Big Data & Pipelines ETL', 'Ingeniería de Datos', 'Buscamos pasante apasionado por el procesamiento de grandes volúmenes de información. Apoyarás en el diseño de pipelines ETL con Python (Pandas/PySpark) e ingesta de fuentes heterogéneas.', E'- Estudiante de Ciencia de Datos, Software o afines.\n- Manejo avanzado de Python (Pandas, NumPy) y consultas SQL.\n- Nociones de arquitecturas Data Lake y procesamiento distribuido.\n- Capacidad analítica y resolución de cuellos de botella de datos.', 'Remoto', 'Guayaquil', 240, 6, 'Lunes a Viernes 09:00 a 15:00', 2, true, '2027-12-31 00:00:00', '2026-06-03 23:07:05', '2026-06-03 23:07:05');
INSERT INTO public.vacantes (vacante_id, institucion_id, supervisor_id, titulo, area, descripcion, requisitos, modalidad, ubicacion, total_horas, horas_diarias, horario, cupos, activo, fecha_expiracion, creado_en, actualizado_en) VALUES (14, 14, 14, 'Pasante de Lean Manufacturing & Mejora Continua', 'Ingeniería de la Producción', 'Buscamos estudiante de Ing. en Producción para colaborar en la optimización de líneas de ensamble, aplicación de metodologías 5S, Kaizen y mapeo de flujo de valor (VSM).', E'- Estudiante de 7mo semestre en adelante de Ing. de la Producción o Industrial.\n- Conocimientos teóricos de metodologías Lean Manufacturing y Six Sigma.\n- Manejo avanzado de Excel y herramientas estadísticas.\n- Proactividad y liderazgo en planta.', 'Presencial', 'Durán', 240, 6, 'Lunes a Viernes 07:00 a 13:00', 2, true, '2027-12-31 00:00:00', '2026-06-03 23:07:05', '2026-06-03 23:07:05');
INSERT INTO public.vacantes (vacante_id, institucion_id, supervisor_id, titulo, area, descripcion, requisitos, modalidad, ubicacion, total_horas, horas_diarias, horario, cupos, activo, fecha_expiracion, creado_en, actualizado_en) VALUES (15, 15, 15, 'Pasante de Automatización de Procesos Operativos', 'Producción & Operaciones', 'Práctica profesional orientada a la digitalización y automatización de flujo de materiales y control de inventarios. Participarás en la estandarización de procesos y reducción de desperdicios.', E'- Estudiante de Ing. en Producción o carreras industriales.\n- Interés en tecnologías de automatización y gestión logística.\n- Dominio de herramientas informáticas de gestión de procesos.\n- Habilidad de análisis de tiempos y movimientos.', 'Presencial', 'Durán', 240, 6, 'Lunes a Viernes 07:00 a 13:00', 2, true, '2027-12-31 00:00:00', '2026-06-03 23:07:05', '2026-06-03 23:07:05');
INSERT INTO public.vacantes (vacante_id, institucion_id, supervisor_id, titulo, area, descripcion, requisitos, modalidad, ubicacion, total_horas, horas_diarias, horario, cupos, activo, fecha_expiracion, creado_en, actualizado_en) VALUES (16, 1, 1, 'Administrador de Redes & Infraestructura de Telecom', 'Redes y Telecomunicaciones', 'Práctica en gestión y soporte de infraestructura de comunicaciones de red. Configuración de routers, switches, reglas de firewall y monitoreo de tráfico institucional.', E'- Estudiante de Telecomunicaciones, Redes o Sistemas.\n- Conocimientos de modelo OSI, TCP/IP y direccionamiento IPv4/IPv6.\n- Manejo básico de equipos Cisco o MikroTik.\n- Disposición para trabajo técnico en campo y configuración remota.', 'Presencial', 'Guayaquil', 144, 6, 'Lunes a Viernes 08:00 a 14:00', 2, true, '2026-07-03 00:00:00', '2026-06-04 18:36:44', '2026-06-12 00:11:28');
INSERT INTO public.vacantes (vacante_id, institucion_id, supervisor_id, titulo, area, descripcion, requisitos, modalidad, ubicacion, total_horas, horas_diarias, horario, cupos, activo, fecha_expiracion, creado_en, actualizado_en) VALUES (24, 2, 2, 'Practicas en Desarrollo de Software Multiplataforma', 'Desarrollo', 'Apoyo en el desarrollo de aplicaciones. Tareas orientadas a la integracion de interfaces frontend y manipulacion de bases de datos con SQL y pyhton para el backend.', 'Manejo de pyhton, SQL y Data Analysis. Uso de Adobe XD para diseno de interfaces.', 'Presencial', 'Quito', 160, 6, 'Lunes a Viernes 09:00 a 15:00', 1, true, '2027-12-31 00:00:00', '2026-06-16 22:47:55', '2026-06-16 22:47:55');
INSERT INTO public.vacantes (vacante_id, institucion_id, supervisor_id, titulo, area, descripcion, requisitos, modalidad, ubicacion, total_horas, horas_diarias, horario, cupos, activo, fecha_expiracion, creado_en, actualizado_en) VALUES (23, 2, 2, 'Practicas en Data Science e IA', 'Tecnología', 'Participacion en el analisis profundo de informacion y creacion de sistemas inteligentes. Apoyo en el entrenamiento de redes neuronales y algoritmos de aprendizaje automatico para extraer valor de los datos.', 'Conocimiento en Data Science y Machine Learning. Manejo de pyhton y SQL. Interes en analisis estadistico y modelos de IA avanzados.', 'Remoto', 'Guayaquil', 160, 6, 'Lunes a Viernes 09:00 a 15:00', 2, true, '2027-12-31 00:00:00', '2026-06-16 22:47:55', '2026-06-16 22:47:55');
INSERT INTO public.vacantes (vacante_id, institucion_id, supervisor_id, titulo, area, descripcion, requisitos, modalidad, ubicacion, total_horas, horas_diarias, horario, cupos, activo, fecha_expiracion, creado_en, actualizado_en) VALUES (5, 5, 5, 'Desarrollador Backend PHP & Framework Laravel', 'Sistemas de Información', 'Participa en el mantenimiento evolutivo y creación de nuevos módulos web utilizando PHP 8 y Laravel. Apoyarás en el diseño de arquitectura MVC, migraciones de base de datos e integración con paneles administrativos.', E'- Estudiante de 6to semestre en adelante en Software/Sistemas.\n- Manejo básico o intermedio de PHP y POO.\n- Nociones de desarrollo web con Laravel o frameworks MVC.\n- Manejo de motores de base de datos MySQL o PostgreSQL.', 'Presencial', 'Samborondón', 240, 6, 'Lunes a Viernes 08:30 a 14:30', 2, true, '2027-12-31 00:00:00', '2026-06-03 23:07:05', '2026-06-03 23:07:05');
INSERT INTO public.vacantes (vacante_id, institucion_id, supervisor_id, titulo, area, descripcion, requisitos, modalidad, ubicacion, total_horas, horas_diarias, horario, cupos, activo, fecha_expiracion, creado_en, actualizado_en) VALUES (9, 9, 9, 'Desarrollador de Integraciones Backend & ERP', 'Sistemas Empresariales', 'Participa en la interconexión de sistemas ERP y bases de datos transaccionales de la empresa. Desarrollarás pipelines de sincronización de datos y webhooks para automatizar procesos financieros y operativos.', E'- Estudiante de últimos semestres de Ing. en Software o Sistemas.\n- Sólido manejo de SQL (procedimientos almacenados, triggers, vistas).\n- Experiencia en lenguaje backend (Python, C# o Java).\n- Orientación al orden y estructura de datos empresarial.', 'Presencial', 'Guayaquil', 240, 6, 'Lunes a Viernes 08:00 a 14:00', 2, true, '2027-12-31 00:00:00', '2026-06-03 23:07:05', '2026-06-03 23:07:05');
INSERT INTO public.vacantes (vacante_id, institucion_id, supervisor_id, titulo, area, descripcion, requisitos, modalidad, ubicacion, total_horas, horas_diarias, horario, cupos, activo, fecha_expiracion, creado_en, actualizado_en) VALUES (13, 13, 13, 'Analista Estadístico & Modelación de Métricas', 'Ciencia de Datos', 'Únete al equipo analítico para realizar análisis exploratorio de datos (EDA), pruebas de hipótesis estadísticas y construcción de modelos predictivos básicos para optimización del negocio.', E'- Estudiante de Ciencia de Datos, Estadística o Software.\n- Sólidas bases de estadística descriptiva e inferencial.\n- Manejo de Python o R para análisis estadístico.\n- Capacidad de documentación y elaboración de conclusiones fundamentadas.', 'Remoto', 'Guayaquil', 240, 6, 'Lunes a Viernes 09:00 a 15:00', 2, true, '2027-12-31 00:00:00', '2026-06-03 23:07:05', '2026-06-03 23:07:05');
INSERT INTO public.vacantes (vacante_id, institucion_id, supervisor_id, titulo, area, descripcion, requisitos, modalidad, ubicacion, total_horas, horas_diarias, horario, cupos, activo, fecha_expiracion, creado_en, actualizado_en) VALUES (25, 2, 2, 'Practicas en Ingenieria de Datos y Backend', 'Backend', 'Desarrollo de pipelines de datos y microservicios orientados al analisis de informacion en el ecosistema Microsoft. Apoyo en la arquitectura de software.', 'Conocimientos en .NET y bases de datos relacionales como SQL. Interes en la implementacion de algoritmos.', 'Híbrido', 'Cuenca', 160, 6, 'Lunes a Viernes 09:00 a 15:00', 3, true, '2027-12-31 00:00:00', '2026-06-16 22:47:55', '2026-06-16 22:47:55');

-- ==========================================
-- DATOS TABLA: public.habilidades
-- ==========================================
INSERT INTO public.habilidades (habilidad_id, nombre, categoria) VALUES (1, 'JavaScript', 'Programacion');
INSERT INTO public.habilidades (habilidad_id, nombre, categoria) VALUES (2, 'Python', 'Programacion');
INSERT INTO public.habilidades (habilidad_id, nombre, categoria) VALUES (3, 'React', 'Frontend');
INSERT INTO public.habilidades (habilidad_id, nombre, categoria) VALUES (4, 'Node.js', 'Backend');
INSERT INTO public.habilidades (habilidad_id, nombre, categoria) VALUES (5, 'SQL', 'Base de Datos');
INSERT INTO public.habilidades (habilidad_id, nombre, categoria) VALUES (6, 'Java', 'Programacion');
INSERT INTO public.habilidades (habilidad_id, nombre, categoria) VALUES (7, 'TypeScript', 'Programacion');
INSERT INTO public.habilidades (habilidad_id, nombre, categoria) VALUES (8, 'Git', 'Herramientas');
INSERT INTO public.habilidades (habilidad_id, nombre, categoria) VALUES (9, 'Excel', 'Herramientas');
INSERT INTO public.habilidades (habilidad_id, nombre, categoria) VALUES (10, 'Power BI', 'Analisis');
INSERT INTO public.habilidades (habilidad_id, nombre, categoria) VALUES (11, 'Figma', 'Diseno');
INSERT INTO public.habilidades (habilidad_id, nombre, categoria) VALUES (12, 'Adobe XD', 'Diseno');
INSERT INTO public.habilidades (habilidad_id, nombre, categoria) VALUES (13, 'Machine Learning', 'IA');
INSERT INTO public.habilidades (habilidad_id, nombre, categoria) VALUES (14, 'Data Analysis', 'Analisis');
INSERT INTO public.habilidades (habilidad_id, nombre, categoria) VALUES (15, 'AWS', 'Cloud');
INSERT INTO public.habilidades (habilidad_id, nombre, categoria) VALUES (16, 'Docker', 'DevOps');
INSERT INTO public.habilidades (habilidad_id, nombre, categoria) VALUES (17, 'Ingles', 'Idiomas');
INSERT INTO public.habilidades (habilidad_id, nombre, categoria) VALUES (18, 'Liderazgo', 'Soft Skills');
INSERT INTO public.habilidades (habilidad_id, nombre, categoria) VALUES (19, 'Trabajo en equipo', 'Soft Skills');
INSERT INTO public.habilidades (habilidad_id, nombre, categoria) VALUES (20, 'Comunicacion', 'Soft Skills');
INSERT INTO public.habilidades (habilidad_id, nombre, categoria) VALUES (21, 'Flask', 'Backend');
INSERT INTO public.habilidades (habilidad_id, nombre, categoria) VALUES (22, 'Django', 'Backend');
INSERT INTO public.habilidades (habilidad_id, nombre, categoria) VALUES (23, 'C#', 'Programacion');
INSERT INTO public.habilidades (habilidad_id, nombre, categoria) VALUES (24, '.NET', 'Backend');
INSERT INTO public.habilidades (habilidad_id, nombre, categoria) VALUES (25, 'PHP', 'Programacion');
INSERT INTO public.habilidades (habilidad_id, nombre, categoria) VALUES (26, 'Laravel', 'Backend');
INSERT INTO public.habilidades (habilidad_id, nombre, categoria) VALUES (27, 'Angular', 'Frontend');
INSERT INTO public.habilidades (habilidad_id, nombre, categoria) VALUES (28, 'Vue.js', 'Frontend');
INSERT INTO public.habilidades (habilidad_id, nombre, categoria) VALUES (29, 'PostgreSQL', 'Base de Datos');
INSERT INTO public.habilidades (habilidad_id, nombre, categoria) VALUES (30, 'MongoDB', 'Base de Datos');
INSERT INTO public.habilidades (habilidad_id, nombre, categoria) VALUES (31, 'TensorFlow', 'IA');
INSERT INTO public.habilidades (habilidad_id, nombre, categoria) VALUES (32, 'PyTorch', 'IA');
INSERT INTO public.habilidades (habilidad_id, nombre, categoria) VALUES (33, 'Lean Manufacturing', 'Ingenieria');
INSERT INTO public.habilidades (habilidad_id, nombre, categoria) VALUES (34, 'Six Sigma', 'Ingenieria');
INSERT INTO public.habilidades (habilidad_id, nombre, categoria) VALUES (35, 'Logistica', 'Ingenieria');
INSERT INTO public.habilidades (habilidad_id, nombre, categoria) VALUES (36, 'pyhton', 'Manual');
INSERT INTO public.habilidades (habilidad_id, nombre, categoria) VALUES (37, 'Data Science', NULL);
INSERT INTO public.habilidades (habilidad_id, nombre, categoria) VALUES (38, 'Flutter', NULL);
INSERT INTO public.habilidades (habilidad_id, nombre, categoria) VALUES (39, 'CSS', NULL);
INSERT INTO public.habilidades (habilidad_id, nombre, categoria) VALUES (40, 'depp learning', 'Manual');
INSERT INTO public.habilidades (habilidad_id, nombre, categoria) VALUES (41, 'html', 'Manual');
INSERT INTO public.habilidades (habilidad_id, nombre, categoria) VALUES (42, 'REST API', 'Manual');
INSERT INTO public.habilidades (habilidad_id, nombre, categoria) VALUES (43, 'GitHub', 'Manual');
INSERT INTO public.habilidades (habilidad_id, nombre, categoria) VALUES (44, 'git hub', 'Manual');
INSERT INTO public.habilidades (habilidad_id, nombre, categoria) VALUES (45, 'node', 'Manual');
INSERT INTO public.habilidades (habilidad_id, nombre, categoria) VALUES (46, 'Base de datos', 'Manual');

-- ==========================================
-- DATOS TABLA: public.habilidades_estudiante
-- ==========================================
INSERT INTO public.habilidades_estudiante (id, estudiante_id, habilidad_id, nivel) VALUES (921, 2, 3, 3);
INSERT INTO public.habilidades_estudiante (id, estudiante_id, habilidad_id, nivel) VALUES (922, 2, 4, 3);
INSERT INTO public.habilidades_estudiante (id, estudiante_id, habilidad_id, nivel) VALUES (923, 2, 5, 3);
INSERT INTO public.habilidades_estudiante (id, estudiante_id, habilidad_id, nivel) VALUES (924, 2, 27, 3);
INSERT INTO public.habilidades_estudiante (id, estudiante_id, habilidad_id, nivel) VALUES (925, 2, 39, 3);
INSERT INTO public.habilidades_estudiante (id, estudiante_id, habilidad_id, nivel) VALUES (926, 2, 41, 3);
INSERT INTO public.habilidades_estudiante (id, estudiante_id, habilidad_id, nivel) VALUES (7, 3, 1, 4);
INSERT INTO public.habilidades_estudiante (id, estudiante_id, habilidad_id, nivel) VALUES (8, 3, 3, 4);
INSERT INTO public.habilidades_estudiante (id, estudiante_id, habilidad_id, nivel) VALUES (9, 3, 4, 3);
INSERT INTO public.habilidades_estudiante (id, estudiante_id, habilidad_id, nivel) VALUES (10, 4, 1, 4);
INSERT INTO public.habilidades_estudiante (id, estudiante_id, habilidad_id, nivel) VALUES (11, 4, 3, 4);
INSERT INTO public.habilidades_estudiante (id, estudiante_id, habilidad_id, nivel) VALUES (12, 4, 4, 3);
INSERT INTO public.habilidades_estudiante (id, estudiante_id, habilidad_id, nivel) VALUES (13, 5, 1, 4);
INSERT INTO public.habilidades_estudiante (id, estudiante_id, habilidad_id, nivel) VALUES (14, 5, 3, 4);
INSERT INTO public.habilidades_estudiante (id, estudiante_id, habilidad_id, nivel) VALUES (15, 5, 4, 3);
INSERT INTO public.habilidades_estudiante (id, estudiante_id, habilidad_id, nivel) VALUES (16, 6, 2, 5);
INSERT INTO public.habilidades_estudiante (id, estudiante_id, habilidad_id, nivel) VALUES (17, 6, 13, 4);
INSERT INTO public.habilidades_estudiante (id, estudiante_id, habilidad_id, nivel) VALUES (18, 6, 14, 4);
INSERT INTO public.habilidades_estudiante (id, estudiante_id, habilidad_id, nivel) VALUES (19, 7, 2, 5);
INSERT INTO public.habilidades_estudiante (id, estudiante_id, habilidad_id, nivel) VALUES (20, 7, 13, 4);
INSERT INTO public.habilidades_estudiante (id, estudiante_id, habilidad_id, nivel) VALUES (21, 7, 14, 4);
INSERT INTO public.habilidades_estudiante (id, estudiante_id, habilidad_id, nivel) VALUES (22, 8, 33, 4);
INSERT INTO public.habilidades_estudiante (id, estudiante_id, habilidad_id, nivel) VALUES (23, 8, 34, 3);
INSERT INTO public.habilidades_estudiante (id, estudiante_id, habilidad_id, nivel) VALUES (24, 8, 35, 4);
INSERT INTO public.habilidades_estudiante (id, estudiante_id, habilidad_id, nivel) VALUES (25, 9, 33, 4);
INSERT INTO public.habilidades_estudiante (id, estudiante_id, habilidad_id, nivel) VALUES (26, 9, 34, 3);
INSERT INTO public.habilidades_estudiante (id, estudiante_id, habilidad_id, nivel) VALUES (27, 9, 35, 4);
INSERT INTO public.habilidades_estudiante (id, estudiante_id, habilidad_id, nivel) VALUES (28, 10, 33, 4);
INSERT INTO public.habilidades_estudiante (id, estudiante_id, habilidad_id, nivel) VALUES (29, 10, 34, 3);
INSERT INTO public.habilidades_estudiante (id, estudiante_id, habilidad_id, nivel) VALUES (30, 10, 35, 4);
INSERT INTO public.habilidades_estudiante (id, estudiante_id, habilidad_id, nivel) VALUES (927, 2, 42, 3);
INSERT INTO public.habilidades_estudiante (id, estudiante_id, habilidad_id, nivel) VALUES (928, 2, 43, 3);
INSERT INTO public.habilidades_estudiante (id, estudiante_id, habilidad_id, nivel) VALUES (376, 1, 5, 3);
INSERT INTO public.habilidades_estudiante (id, estudiante_id, habilidad_id, nivel) VALUES (377, 1, 12, 3);
INSERT INTO public.habilidades_estudiante (id, estudiante_id, habilidad_id, nivel) VALUES (378, 1, 13, 1);
INSERT INTO public.habilidades_estudiante (id, estudiante_id, habilidad_id, nivel) VALUES (379, 1, 14, 3);
INSERT INTO public.habilidades_estudiante (id, estudiante_id, habilidad_id, nivel) VALUES (380, 1, 20, 3);
INSERT INTO public.habilidades_estudiante (id, estudiante_id, habilidad_id, nivel) VALUES (381, 1, 36, 3);
INSERT INTO public.habilidades_estudiante (id, estudiante_id, habilidad_id, nivel) VALUES (382, 1, 37, 1);
INSERT INTO public.habilidades_estudiante (id, estudiante_id, habilidad_id, nivel) VALUES (383, 1, 40, 3);
INSERT INTO public.habilidades_estudiante (id, estudiante_id, habilidad_id, nivel) VALUES (384, 1, 22, 3);
INSERT INTO public.habilidades_estudiante (id, estudiante_id, habilidad_id, nivel) VALUES (385, 1, 16, 3);
INSERT INTO public.habilidades_estudiante (id, estudiante_id, habilidad_id, nivel) VALUES (386, 1, 9, 3);

-- ==========================================
-- DATOS TABLA: public.habilidades_vacante
-- ==========================================
INSERT INTO public.habilidades_vacante (id, vacante_id, habilidad_id, nivel_requerido, es_opcional) VALUES (1, 1, 4, 1, false);
INSERT INTO public.habilidades_vacante (id, vacante_id, habilidad_id, nivel_requerido, es_opcional) VALUES (2, 1, 5, 1, false);
INSERT INTO public.habilidades_vacante (id, vacante_id, habilidad_id, nivel_requerido, es_opcional) VALUES (3, 1, 8, 1, false);
INSERT INTO public.habilidades_vacante (id, vacante_id, habilidad_id, nivel_requerido, es_opcional) VALUES (4, 2, 4, 1, false);
INSERT INTO public.habilidades_vacante (id, vacante_id, habilidad_id, nivel_requerido, es_opcional) VALUES (5, 2, 5, 1, false);
INSERT INTO public.habilidades_vacante (id, vacante_id, habilidad_id, nivel_requerido, es_opcional) VALUES (6, 2, 8, 1, false);
INSERT INTO public.habilidades_vacante (id, vacante_id, habilidad_id, nivel_requerido, es_opcional) VALUES (7, 3, 4, 1, false);
INSERT INTO public.habilidades_vacante (id, vacante_id, habilidad_id, nivel_requerido, es_opcional) VALUES (8, 3, 5, 1, false);
INSERT INTO public.habilidades_vacante (id, vacante_id, habilidad_id, nivel_requerido, es_opcional) VALUES (9, 3, 8, 1, false);
INSERT INTO public.habilidades_vacante (id, vacante_id, habilidad_id, nivel_requerido, es_opcional) VALUES (10, 4, 4, 1, false);
INSERT INTO public.habilidades_vacante (id, vacante_id, habilidad_id, nivel_requerido, es_opcional) VALUES (11, 4, 5, 1, false);
INSERT INTO public.habilidades_vacante (id, vacante_id, habilidad_id, nivel_requerido, es_opcional) VALUES (12, 4, 8, 1, false);
INSERT INTO public.habilidades_vacante (id, vacante_id, habilidad_id, nivel_requerido, es_opcional) VALUES (13, 5, 4, 1, false);
INSERT INTO public.habilidades_vacante (id, vacante_id, habilidad_id, nivel_requerido, es_opcional) VALUES (14, 5, 5, 1, false);
INSERT INTO public.habilidades_vacante (id, vacante_id, habilidad_id, nivel_requerido, es_opcional) VALUES (15, 5, 8, 1, false);
INSERT INTO public.habilidades_vacante (id, vacante_id, habilidad_id, nivel_requerido, es_opcional) VALUES (16, 6, 4, 1, false);
INSERT INTO public.habilidades_vacante (id, vacante_id, habilidad_id, nivel_requerido, es_opcional) VALUES (17, 6, 5, 1, false);
INSERT INTO public.habilidades_vacante (id, vacante_id, habilidad_id, nivel_requerido, es_opcional) VALUES (18, 6, 8, 1, false);
INSERT INTO public.habilidades_vacante (id, vacante_id, habilidad_id, nivel_requerido, es_opcional) VALUES (19, 7, 4, 1, false);
INSERT INTO public.habilidades_vacante (id, vacante_id, habilidad_id, nivel_requerido, es_opcional) VALUES (20, 7, 5, 1, false);
INSERT INTO public.habilidades_vacante (id, vacante_id, habilidad_id, nivel_requerido, es_opcional) VALUES (21, 7, 8, 1, false);
INSERT INTO public.habilidades_vacante (id, vacante_id, habilidad_id, nivel_requerido, es_opcional) VALUES (22, 8, 4, 1, false);
INSERT INTO public.habilidades_vacante (id, vacante_id, habilidad_id, nivel_requerido, es_opcional) VALUES (23, 8, 5, 1, false);
INSERT INTO public.habilidades_vacante (id, vacante_id, habilidad_id, nivel_requerido, es_opcional) VALUES (24, 8, 8, 1, false);
INSERT INTO public.habilidades_vacante (id, vacante_id, habilidad_id, nivel_requerido, es_opcional) VALUES (25, 9, 4, 1, false);
INSERT INTO public.habilidades_vacante (id, vacante_id, habilidad_id, nivel_requerido, es_opcional) VALUES (26, 9, 5, 1, false);
INSERT INTO public.habilidades_vacante (id, vacante_id, habilidad_id, nivel_requerido, es_opcional) VALUES (27, 9, 8, 1, false);
INSERT INTO public.habilidades_vacante (id, vacante_id, habilidad_id, nivel_requerido, es_opcional) VALUES (31, 11, 2, 1, false);
INSERT INTO public.habilidades_vacante (id, vacante_id, habilidad_id, nivel_requerido, es_opcional) VALUES (32, 11, 14, 1, false);
INSERT INTO public.habilidades_vacante (id, vacante_id, habilidad_id, nivel_requerido, es_opcional) VALUES (33, 11, 10, 1, false);
INSERT INTO public.habilidades_vacante (id, vacante_id, habilidad_id, nivel_requerido, es_opcional) VALUES (34, 12, 2, 1, false);
INSERT INTO public.habilidades_vacante (id, vacante_id, habilidad_id, nivel_requerido, es_opcional) VALUES (35, 12, 14, 1, false);
INSERT INTO public.habilidades_vacante (id, vacante_id, habilidad_id, nivel_requerido, es_opcional) VALUES (36, 12, 10, 1, false);
INSERT INTO public.habilidades_vacante (id, vacante_id, habilidad_id, nivel_requerido, es_opcional) VALUES (37, 13, 2, 1, false);
INSERT INTO public.habilidades_vacante (id, vacante_id, habilidad_id, nivel_requerido, es_opcional) VALUES (38, 13, 14, 1, false);
INSERT INTO public.habilidades_vacante (id, vacante_id, habilidad_id, nivel_requerido, es_opcional) VALUES (39, 13, 10, 1, false);
INSERT INTO public.habilidades_vacante (id, vacante_id, habilidad_id, nivel_requerido, es_opcional) VALUES (40, 14, 9, 1, false);
INSERT INTO public.habilidades_vacante (id, vacante_id, habilidad_id, nivel_requerido, es_opcional) VALUES (41, 14, 33, 1, false);
INSERT INTO public.habilidades_vacante (id, vacante_id, habilidad_id, nivel_requerido, es_opcional) VALUES (42, 14, 19, 1, false);
INSERT INTO public.habilidades_vacante (id, vacante_id, habilidad_id, nivel_requerido, es_opcional) VALUES (43, 15, 9, 1, false);
INSERT INTO public.habilidades_vacante (id, vacante_id, habilidad_id, nivel_requerido, es_opcional) VALUES (44, 15, 33, 1, false);
INSERT INTO public.habilidades_vacante (id, vacante_id, habilidad_id, nivel_requerido, es_opcional) VALUES (45, 15, 19, 1, false);
INSERT INTO public.habilidades_vacante (id, vacante_id, habilidad_id, nivel_requerido, es_opcional) VALUES (196, 10, 8, 1, false);
INSERT INTO public.habilidades_vacante (id, vacante_id, habilidad_id, nivel_requerido, es_opcional) VALUES (197, 10, 41, 3, false);
INSERT INTO public.habilidades_vacante (id, vacante_id, habilidad_id, nivel_requerido, es_opcional) VALUES (198, 10, 1, 3, false);
INSERT INTO public.habilidades_vacante (id, vacante_id, habilidad_id, nivel_requerido, es_opcional) VALUES (199, 10, 39, 3, false);
INSERT INTO public.habilidades_vacante (id, vacante_id, habilidad_id, nivel_requerido, es_opcional) VALUES (200, 10, 42, 3, false);
INSERT INTO public.habilidades_vacante (id, vacante_id, habilidad_id, nivel_requerido, es_opcional) VALUES (56, 16, 6, 5, false);
INSERT INTO public.habilidades_vacante (id, vacante_id, habilidad_id, nivel_requerido, es_opcional) VALUES (57, 17, 36, 3, false);
INSERT INTO public.habilidades_vacante (id, vacante_id, habilidad_id, nivel_requerido, es_opcional) VALUES (58, 17, 14, 3, false);
INSERT INTO public.habilidades_vacante (id, vacante_id, habilidad_id, nivel_requerido, es_opcional) VALUES (59, 17, 1, 3, false);
INSERT INTO public.habilidades_vacante (id, vacante_id, habilidad_id, nivel_requerido, es_opcional) VALUES (201, 10, 43, 3, false);
INSERT INTO public.habilidades_vacante (id, vacante_id, habilidad_id, nivel_requerido, es_opcional) VALUES (202, 10, 3, 3, false);
INSERT INTO public.habilidades_vacante (id, vacante_id, habilidad_id, nivel_requerido, es_opcional) VALUES (203, 10, 27, 3, false);
INSERT INTO public.habilidades_vacante (id, vacante_id, habilidad_id, nivel_requerido, es_opcional) VALUES (73, 23, 13, 2, false);
INSERT INTO public.habilidades_vacante (id, vacante_id, habilidad_id, nivel_requerido, es_opcional) VALUES (74, 23, 37, 2, false);
INSERT INTO public.habilidades_vacante (id, vacante_id, habilidad_id, nivel_requerido, es_opcional) VALUES (75, 23, 36, 2, false);
INSERT INTO public.habilidades_vacante (id, vacante_id, habilidad_id, nivel_requerido, es_opcional) VALUES (76, 23, 5, 2, false);
INSERT INTO public.habilidades_vacante (id, vacante_id, habilidad_id, nivel_requerido, es_opcional) VALUES (77, 23, 14, 2, false);
INSERT INTO public.habilidades_vacante (id, vacante_id, habilidad_id, nivel_requerido, es_opcional) VALUES (78, 24, 12, 2, false);
INSERT INTO public.habilidades_vacante (id, vacante_id, habilidad_id, nivel_requerido, es_opcional) VALUES (79, 24, 36, 2, false);
INSERT INTO public.habilidades_vacante (id, vacante_id, habilidad_id, nivel_requerido, es_opcional) VALUES (80, 24, 5, 2, false);
INSERT INTO public.habilidades_vacante (id, vacante_id, habilidad_id, nivel_requerido, es_opcional) VALUES (81, 24, 14, 2, false);
INSERT INTO public.habilidades_vacante (id, vacante_id, habilidad_id, nivel_requerido, es_opcional) VALUES (82, 25, 24, 2, false);
INSERT INTO public.habilidades_vacante (id, vacante_id, habilidad_id, nivel_requerido, es_opcional) VALUES (83, 25, 5, 2, false);
INSERT INTO public.habilidades_vacante (id, vacante_id, habilidad_id, nivel_requerido, es_opcional) VALUES (84, 25, 23, 2, false);
INSERT INTO public.habilidades_vacante (id, vacante_id, habilidad_id, nivel_requerido, es_opcional) VALUES (85, 25, 14, 2, false);
INSERT INTO public.habilidades_vacante (id, vacante_id, habilidad_id, nivel_requerido, es_opcional) VALUES (128, 26, 38, 3, false);
INSERT INTO public.habilidades_vacante (id, vacante_id, habilidad_id, nivel_requerido, es_opcional) VALUES (129, 26, 22, 3, false);
INSERT INTO public.habilidades_vacante (id, vacante_id, habilidad_id, nivel_requerido, es_opcional) VALUES (130, 26, 16, 3, false);
INSERT INTO public.habilidades_vacante (id, vacante_id, habilidad_id, nivel_requerido, es_opcional) VALUES (131, 26, 9, 3, false);
INSERT INTO public.habilidades_vacante (id, vacante_id, habilidad_id, nivel_requerido, es_opcional) VALUES (132, 26, 23, 3, false);
INSERT INTO public.habilidades_vacante (id, vacante_id, habilidad_id, nivel_requerido, es_opcional) VALUES (133, 26, 15, 3, false);
INSERT INTO public.habilidades_vacante (id, vacante_id, habilidad_id, nivel_requerido, es_opcional) VALUES (134, 26, 40, 3, false);
INSERT INTO public.habilidades_vacante (id, vacante_id, habilidad_id, nivel_requerido, es_opcional) VALUES (135, 18, 2, 1, false);
INSERT INTO public.habilidades_vacante (id, vacante_id, habilidad_id, nivel_requerido, es_opcional) VALUES (136, 18, 13, 1, false);
INSERT INTO public.habilidades_vacante (id, vacante_id, habilidad_id, nivel_requerido, es_opcional) VALUES (137, 18, 37, 1, false);
INSERT INTO public.habilidades_vacante (id, vacante_id, habilidad_id, nivel_requerido, es_opcional) VALUES (138, 18, 5, 1, false);

-- ==========================================
-- DATOS TABLA: public.cache_afinidad
-- ==========================================
INSERT INTO public.cache_afinidad (id, estudiante_id, vacante_id, porcentaje_afinidad, calculado_en) VALUES (436, 1, 23, '79.11', '2026-06-18 12:26:21');
INSERT INTO public.cache_afinidad (id, estudiante_id, vacante_id, porcentaje_afinidad, calculado_en) VALUES (898, 3, 18, '7.07', '2026-07-09 00:16:24');
INSERT INTO public.cache_afinidad (id, estudiante_id, vacante_id, porcentaje_afinidad, calculado_en) VALUES (899, 4, 18, '7.07', '2026-07-09 00:16:25');
INSERT INTO public.cache_afinidad (id, estudiante_id, vacante_id, porcentaje_afinidad, calculado_en) VALUES (900, 5, 18, '7.07', '2026-07-09 00:16:25');
INSERT INTO public.cache_afinidad (id, estudiante_id, vacante_id, porcentaje_afinidad, calculado_en) VALUES (448, 1, 14, '7.38', '2026-06-18 12:26:22');
INSERT INTO public.cache_afinidad (id, estudiante_id, vacante_id, porcentaje_afinidad, calculado_en) VALUES (449, 1, 15, '7.38', '2026-06-18 12:26:22');
INSERT INTO public.cache_afinidad (id, estudiante_id, vacante_id, porcentaje_afinidad, calculado_en) VALUES (901, 6, 18, '69.68', '2026-07-09 00:16:26');
INSERT INTO public.cache_afinidad (id, estudiante_id, vacante_id, porcentaje_afinidad, calculado_en) VALUES (438, 1, 18, '59.61', '2026-07-09 00:16:26');
INSERT INTO public.cache_afinidad (id, estudiante_id, vacante_id, porcentaje_afinidad, calculado_en) VALUES (803, 7, 18, '69.68', '2026-07-09 00:16:27');
INSERT INTO public.cache_afinidad (id, estudiante_id, vacante_id, porcentaje_afinidad, calculado_en) VALUES (657, 3, 26, '33.18', '2026-06-22 00:04:04');
INSERT INTO public.cache_afinidad (id, estudiante_id, vacante_id, porcentaje_afinidad, calculado_en) VALUES (658, 4, 26, '33.18', '2026-06-22 00:04:05');
INSERT INTO public.cache_afinidad (id, estudiante_id, vacante_id, porcentaje_afinidad, calculado_en) VALUES (659, 5, 26, '33.18', '2026-06-22 00:04:05');
INSERT INTO public.cache_afinidad (id, estudiante_id, vacante_id, porcentaje_afinidad, calculado_en) VALUES (660, 6, 26, '8.71', '2026-06-22 00:04:06');
INSERT INTO public.cache_afinidad (id, estudiante_id, vacante_id, porcentaje_afinidad, calculado_en) VALUES (949, 3, 10, '48.64', '2026-07-21 13:27:57');
INSERT INTO public.cache_afinidad (id, estudiante_id, vacante_id, porcentaje_afinidad, calculado_en) VALUES (950, 4, 10, '48.64', '2026-07-21 13:27:57');
INSERT INTO public.cache_afinidad (id, estudiante_id, vacante_id, porcentaje_afinidad, calculado_en) VALUES (951, 5, 10, '48.64', '2026-07-21 13:27:58');
INSERT INTO public.cache_afinidad (id, estudiante_id, vacante_id, porcentaje_afinidad, calculado_en) VALUES (952, 6, 10, '5.82', '2026-07-21 13:27:58');
INSERT INTO public.cache_afinidad (id, estudiante_id, vacante_id, porcentaje_afinidad, calculado_en) VALUES (444, 1, 10, '7.87', '2026-07-21 13:27:59');
INSERT INTO public.cache_afinidad (id, estudiante_id, vacante_id, porcentaje_afinidad, calculado_en) VALUES (662, 7, 26, '18.31', '2026-06-20 11:01:28');
INSERT INTO public.cache_afinidad (id, estudiante_id, vacante_id, porcentaje_afinidad, calculado_en) VALUES (810, 7, 10, '5.82', '2026-07-21 13:27:59');
INSERT INTO public.cache_afinidad (id, estudiante_id, vacante_id, porcentaje_afinidad, calculado_en) VALUES (661, 1, 26, '63.51', '2026-06-24 00:13:11');
INSERT INTO public.cache_afinidad (id, estudiante_id, vacante_id, porcentaje_afinidad, calculado_en) VALUES (437, 1, 25, '47.15', '2026-06-24 00:13:11');
INSERT INTO public.cache_afinidad (id, estudiante_id, vacante_id, porcentaje_afinidad, calculado_en) VALUES (440, 1, 6, '40.79', '2026-06-24 00:13:12');
INSERT INTO public.cache_afinidad (id, estudiante_id, vacante_id, porcentaje_afinidad, calculado_en) VALUES (441, 1, 7, '40.79', '2026-06-24 00:13:12');
INSERT INTO public.cache_afinidad (id, estudiante_id, vacante_id, porcentaje_afinidad, calculado_en) VALUES (442, 1, 8, '40.79', '2026-06-24 00:13:12');
INSERT INTO public.cache_afinidad (id, estudiante_id, vacante_id, porcentaje_afinidad, calculado_en) VALUES (446, 1, 12, '32.32', '2026-06-24 00:13:12');
INSERT INTO public.cache_afinidad (id, estudiante_id, vacante_id, porcentaje_afinidad, calculado_en) VALUES (447, 1, 13, '32.32', '2026-06-24 00:13:12');
INSERT INTO public.cache_afinidad (id, estudiante_id, vacante_id, porcentaje_afinidad, calculado_en) VALUES (451, 1, 2, '40.79', '2026-06-24 00:13:12');
INSERT INTO public.cache_afinidad (id, estudiante_id, vacante_id, porcentaje_afinidad, calculado_en) VALUES (452, 1, 3, '40.79', '2026-06-24 00:13:13');
INSERT INTO public.cache_afinidad (id, estudiante_id, vacante_id, porcentaje_afinidad, calculado_en) VALUES (453, 1, 4, '40.79', '2026-06-24 00:13:13');
INSERT INTO public.cache_afinidad (id, estudiante_id, vacante_id, porcentaje_afinidad, calculado_en) VALUES (802, 7, 25, '32.21', '2026-06-25 23:15:18');
INSERT INTO public.cache_afinidad (id, estudiante_id, vacante_id, porcentaje_afinidad, calculado_en) VALUES (805, 7, 4, '8.88', '2026-06-25 23:15:18');
INSERT INTO public.cache_afinidad (id, estudiante_id, vacante_id, porcentaje_afinidad, calculado_en) VALUES (806, 7, 6, '8.88', '2026-06-25 23:15:18');
INSERT INTO public.cache_afinidad (id, estudiante_id, vacante_id, porcentaje_afinidad, calculado_en) VALUES (807, 7, 7, '8.88', '2026-06-25 23:15:18');
INSERT INTO public.cache_afinidad (id, estudiante_id, vacante_id, porcentaje_afinidad, calculado_en) VALUES (808, 7, 8, '8.88', '2026-06-25 23:15:19');
INSERT INTO public.cache_afinidad (id, estudiante_id, vacante_id, porcentaje_afinidad, calculado_en) VALUES (812, 7, 12, '57.99', '2026-06-25 23:15:19');
INSERT INTO public.cache_afinidad (id, estudiante_id, vacante_id, porcentaje_afinidad, calculado_en) VALUES (813, 7, 13, '57.99', '2026-06-25 23:15:19');
INSERT INTO public.cache_afinidad (id, estudiante_id, vacante_id, porcentaje_afinidad, calculado_en) VALUES (815, 7, 2, '8.88', '2026-06-25 23:15:19');
INSERT INTO public.cache_afinidad (id, estudiante_id, vacante_id, porcentaje_afinidad, calculado_en) VALUES (816, 7, 3, '8.88', '2026-06-25 23:15:19');
INSERT INTO public.cache_afinidad (id, estudiante_id, vacante_id, porcentaje_afinidad, calculado_en) VALUES (1671, 2, 23, '20.84', '2026-07-27 14:33:26');
INSERT INTO public.cache_afinidad (id, estudiante_id, vacante_id, porcentaje_afinidad, calculado_en) VALUES (967, 2, 25, '22.80', '2026-07-27 14:33:26');
INSERT INTO public.cache_afinidad (id, estudiante_id, vacante_id, porcentaje_afinidad, calculado_en) VALUES (1673, 2, 24, '43.67', '2026-07-27 14:33:26');
INSERT INTO public.cache_afinidad (id, estudiante_id, vacante_id, porcentaje_afinidad, calculado_en) VALUES (968, 2, 18, '22.36', '2026-07-27 14:33:26');
INSERT INTO public.cache_afinidad (id, estudiante_id, vacante_id, porcentaje_afinidad, calculado_en) VALUES (1675, 2, 16, '31.49', '2026-07-27 14:33:26');
INSERT INTO public.cache_afinidad (id, estudiante_id, vacante_id, porcentaje_afinidad, calculado_en) VALUES (1676, 2, 5, '56.98', '2026-07-27 14:33:26');
INSERT INTO public.cache_afinidad (id, estudiante_id, vacante_id, porcentaje_afinidad, calculado_en) VALUES (976, 2, 8, '64.00', '2026-07-27 14:33:27');
INSERT INTO public.cache_afinidad (id, estudiante_id, vacante_id, porcentaje_afinidad, calculado_en) VALUES (1678, 2, 11, '6.55', '2026-07-27 14:33:27');
INSERT INTO public.cache_afinidad (id, estudiante_id, vacante_id, porcentaje_afinidad, calculado_en) VALUES (973, 2, 12, '5.40', '2026-07-27 14:33:27');
INSERT INTO public.cache_afinidad (id, estudiante_id, vacante_id, porcentaje_afinidad, calculado_en) VALUES (975, 2, 10, '87.93', '2026-07-27 14:33:27');
INSERT INTO public.cache_afinidad (id, estudiante_id, vacante_id, porcentaje_afinidad, calculado_en) VALUES (970, 2, 6, '52.46', '2026-07-27 14:33:27');
INSERT INTO public.cache_afinidad (id, estudiante_id, vacante_id, porcentaje_afinidad, calculado_en) VALUES (1682, 2, 9, '59.38', '2026-07-27 14:33:27');
INSERT INTO public.cache_afinidad (id, estudiante_id, vacante_id, porcentaje_afinidad, calculado_en) VALUES (971, 2, 7, '55.12', '2026-07-27 14:33:27');
INSERT INTO public.cache_afinidad (id, estudiante_id, vacante_id, porcentaje_afinidad, calculado_en) VALUES (974, 2, 13, '4.94', '2026-07-27 14:33:27');
INSERT INTO public.cache_afinidad (id, estudiante_id, vacante_id, porcentaje_afinidad, calculado_en) VALUES (1685, 2, 1, '57.96', '2026-07-27 14:33:27');
INSERT INTO public.cache_afinidad (id, estudiante_id, vacante_id, porcentaje_afinidad, calculado_en) VALUES (972, 2, 2, '57.99', '2026-07-27 14:33:27');
INSERT INTO public.cache_afinidad (id, estudiante_id, vacante_id, porcentaje_afinidad, calculado_en) VALUES (977, 2, 3, '62.41', '2026-07-27 14:33:27');
INSERT INTO public.cache_afinidad (id, estudiante_id, vacante_id, porcentaje_afinidad, calculado_en) VALUES (969, 2, 4, '54.51', '2026-07-27 14:33:27');
