from marshmallow import Schema, fields

class VacancyRequest(Schema):
    titulo = fields.String(required=False)
    title = fields.String(required=False)
    area = fields.String(required=True)
    descripcion = fields.String(required=False)
    description = fields.String(required=False)
    requisitos = fields.String(required=False)
    requirements = fields.String(required=False)
    modalidad = fields.String(required=False, default='Presencial')
    modality = fields.String(required=False)
    ubicacion = fields.String(required=False)
    location = fields.String(required=False)
    total_horas = fields.Integer(required=False, allow_none=True)
    total_hours = fields.Integer(required=False, allow_none=True)
    horas_diarias = fields.Integer(required=False, allow_none=True)
    daily_hours = fields.Integer(required=False, allow_none=True)
    horario = fields.String(required=False, allow_none=True)
    schedule = fields.String(required=False, allow_none=True)
    cupos = fields.Integer(required=False, default=1)
    slots = fields.Integer(required=False)
    fecha_expiracion = fields.String(required=False)
    expires_at = fields.String(required=False)
    skills = fields.List(fields.Dict(), required=False)